### ISSUE TITLE
Did Media change from .0.0.2?

### ISSUE THREAD

**Issue by syleishere** [alexmercerind/dart_vlc#10]
I had:
     `   List<Media> medias = <Media>[];`
then:
`        medias.add(Media.file(new File(fileSystemEntity.path))); 
`
now its breaking on .3 and .4 versions.

**Comment by alexmercerind** [comment]
Now you need to add `await`, as there are new metadata parsing features in `Media`.

**Comment by syleishere** [comment]
I did have an await, I added it back, same thing, doesn't work....

**Comment by alexmercerind** [comment]
Write this:
```
medias.add(add Media.file(new File(fileSystemEntity.path)));
```

See examples in README

**Comment by syleishere** [comment]
Oww crap this worked though:
await medias.add(await Media.file(new File(fileSystemEntity.path)));

**Comment by alexmercerind** [comment]
Same is documented in README. I make sure to update the examples.

**Comment by syleishere** [comment]
Alright, I can stay on .0.0.4, I'm happy thankyou.

**Comment by syleishere** [comment]
On a side note if you are trying to make similar to audio assets: here is the difference between what you have and what they have so far:

```
import 'package:dart_vlc/dart_vlc.dart';
import 'package:assets_audio_player/assets_audio_player.dart' as myaudio;
```

FOR DART VLC:
`await medias.add(await Media.file(new File(fileSystemEntity.path)));
`FOR AUDIO ASSETS:
`await medias2.add(myaudio.Audio.file(fileSystemEntity.path));
`

Just wondering if done on purpose?
