### ISSUE TITLE
Use texture registrar APIs on iOS, Linux & Mac.

### ISSUE THREAD

**Issue by alexmercerind** [alexmercerind/dart_vlc#107]
- [x] Windows
  - Done.
- [x] Linux
  - Merged #164 
  - Texture support added to engine. https://github.com/flutter/engine/pull/24916.
- [x] macOS
  - Merged #122 
  - Texture support added to engine. https://github.com/flutter/engine/pull/8507
- [ ] iOS
  - Needs to be done. macOS can be used as an example if one wants to work on it.
  - I don't have a mac, please make PR. 🙏
- [ ] Android
  - Android support needs to be worked on. I don't have enough motivation now.

**Comment by alexmercerind** [comment]
@jnschulze are you willing to have look at this sometime in future?

**Comment by jnschulze** [comment]
@alexmercerind Sure, I might find some time next week.

**Comment by lucaszanella** [comment]
How does dart_vlc currently works in linux if linux has no external texture support?

**Comment by alexmercerind** [comment]
@lucaszanella dart_vlc is older than texture APIs on any of Windows, Linux or macOS. I figured out to use `decodeImageFromPixels` and sending buffer frame directly... However, this is not the best in terms of performance, but we have no other choice as of now (I have no idea when they'll merge it).

**Comment by hansihe** [comment]
This seems to be merged on all relevant platforms now, Linux texture support landed earlier today.

**Comment by alexmercerind** [comment]
Raised #254 to target platform-support centrally.
