### ISSUE TITLE
Don't use std::to_string for converting doubles

### ISSUE THREAD

**Issue by jnschulze** [alexmercerind/dart_vlc#111]
...when serializing events on the C++ side as it depends on std::locale.

When testing the player on Linux yesterday, I realized that a double got serialized as `1,23` as opposed to `1.23` which made the playback fail as it couldn't be parsed on the Dart side.

**Comment by alexmercerind** [comment]
@jnschulze We can transfer structs instead of `char**` from C. NativePorts can also send custom data inside Dart `List`s.

**Comment by jnschulze** [comment]
> @jnschulze We can transfer structs instead of `char**` from C. NativePorts can also send custom data inside Dart `List`s.

Yes, this should be the best approach. I can start working on that once I've finished adding macOS support.

**Comment by alexmercerind** [comment]
@jnschulze You may assign me if you wish. I believe I should wait for that PR to be merged first.

**Comment by jnschulze** [comment]
btw., the dart bindings for the corresponding structs might be generated using https://pub.dev/packages/ffigen
