### ISSUE TITLE
PlayerUnegisterTexture

### ISSUE THREAD

**Issue by ymmmvp36** [alexmercerind/dart_vlc#112]
i use this on windows.when i dispose the player.i see this error 'MissingPluginException(No implementation found for method PlayerUnegisterTexture on channel dart_vlc)'.
i find the code 【**await _channel.invokeMethod('PlayerUnegisterTexture', {'playerId': id});**】 in the dart_vlc.dart line 70
and in the dart_vlc_plugin.cpp.it is 【**else if (method_call.method_name() == "PlayerUnregisterTexture") {**】

**Comment by alexmercerind** [comment]
This is the biggest typo I ever made. Apologies.
