### ISSUE TITLE
Video Full Screen Control

### ISSUE THREAD

**Issue by huonsokly** [alexmercerind/dart_vlc#123]
How can I show full screen of video control?

Thank you!

**Comment by alexmercerind** [comment]
This is more of a framework thing instead of VLC related. Still this can be a great thing to implement within the plugin, so keeping it marked as enhancement.

You can use this PR's fork to make your window full-screen. I made this but they didn't merge yet.

**Comment by huonsokly** [comment]
Thank you for information.

**Comment by alexmercerind** [comment]
Use `window_manager`.

**Comment by huonsokly** [comment]
Many Thanks
