### ISSUE TITLE
Player::Open causes crash in release mode.

### ISSUE THREAD

**Issue by huonsokly** [alexmercerind/dart_vlc#124]
I want to change video by click on each videos url.

Player player = Player(id: 123);
String url = 'http://company.com/video/1.mp4';
player.open(
      Media.network(url),
    );

--------------------------

setState(() {
       url = 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
});

Thank you!

**Comment by alexmercerind** [comment]
You must `player.open` again. A new Media object should be created. You are just updating your variable.

**Comment by huonsokly** [comment]
Thank you for your answer!

but when I change to this:

setState(() {
    url = 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
    player.open(Media.network(url));
 });

My application was closed.

**Comment by alexmercerind** [comment]
Please share a reproducible example. Our example application on the repository is able to function very well & I haven't noticed anything wrong.

**Comment by huonsokly** [comment]
Please follow this link: https://github.com/huonsokly/video_dart_vlc/tree/main

Thank you!

**Comment by jnschulze** [comment]
Which OS are we talking about? I've just run your example on a Windows machine and it works without crashing.

But in general you shouldn't call `player.open` inside the build method. I'd rather move this to `initState` etc. What's even more weird to me is that you're performing an unnecessary `setState` in the `onPressed` handler for changing the video URL as this will make your widget rebuild which will in turn load the first video again...

**Comment by huonsokly** [comment]
I do it for Windows

**Comment by jnschulze** [comment]
Okay, then please run the Flutter runner project with an attached debugger and provide us with a stack trace once it crashes.

**Comment by huonsokly** [comment]
When I click on button New Video, it crashes "Lost connection to device."

**Comment by jnschulze** [comment]
Yes, but without a trace we can just guess what the reason is...

**Comment by huonsokly** [comment]
So when you've run and click that's button is it working?

**Comment by jnschulze** [comment]
Yes.

**Comment by alexmercerind** [comment]
Are we talking about master or pub.dev? I don't know if any major changes have happened since then.

**Comment by jnschulze** [comment]
I tried it using the latest master. There have indeed been a few fixes regarding Windows textures after the last release.

**Comment by huonsokly** [comment]
https://drive.google.com/file/d/1qsJ7W0rRCXyTgdYW9sBepPe5g64tmKZk/view

Above is how my application crashes.

**Comment by jnschulze** [comment]
I'm have trouble playing that GIF. Probably due to its size.

- > ...please run the Flutter runner project with **an attached debugger and provide us with a stack trace** once it crashes.


- > Are we talking about master or pub.dev?

**Comment by huonsokly** [comment]
Please play again I've just changed file.

**Comment by jnschulze** [comment]
> Please play again I've just changed file.

Any answers to my questions? 😄

**Comment by huonsokly** [comment]
We are talking about pub.dev.
and about Flutter runner project with an attached debugger, I don't know how to do now.
let me try to do it.

**Comment by jnschulze** [comment]
The easiest way is to just open the Flutter Runner project (which is located within your Flutter project tree) with Visual Studio and run it in debug mode. Or you can open an already built executable with Visual Studio (see https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-an-executable-not-part-of-a-visual-studio-solution?view=vs-2019)

**Comment by alexmercerind** [comment]
@huonsokly you may now try the plugin from master branch, possibly the crash won't happen now.

**Comment by huonsokly** [comment]
after I added and run it shows: 

E:\flutter\talkschool_application\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\mediasource/media.h(20,10): fatal error C1083: Cannot open include file: 'vlcpp/vlc.hpp': No such file or directory [E:\flutter\talkschool_application\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
E:\flutter\talkschool_application\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\device.h(17,10): fatal error C1083: Cannot open include file: 'vlcpp/vlc.hpp': No such file or directory [E:\flutter\talkschool_application\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
Exception: Build process failed.

**Comment by alexmercerind** [comment]
@huonsokly 0.1.6 is published, it will most likely fix your issue.

That error is because git repository needs to be cloned recursively apologies.

**Comment by huonsokly** [comment]
Thank you for your help.
now I'm using: 
dart_vlc: ^0.1.6

--------------------------------------------------------------------------------------------------------------

Player player = Player(id: 123);
String url = 'http://api.talkschool-cambodia.com/video/1627925251.mp4';
--------------------------------------------------------------------------------------------------------------

@override
  void initState() {
    // TODO: implement initState
    super.initState();
    player.open(Media.network(url));
  }

--------------------------------------------------------------------------------------------------------------

ElevatedButton(
  onPressed: () {
      player.open(Media.network('https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4'));
  },
  child: Text("Video 1"),
),

But It's still crashes.

**Comment by a-v-ebrahimi** [comment]
I have same issue, the video plays in debug mode, but in release mode playing a video will crash the app.

**Comment by alexmercerind** [comment]
@a-v-ebrahimi

- Are you on latest v0.1.6?
- Do you mind sharing code that can reproduce the issue? (for me to check the callstack in Visual Studio).

**Comment by a-v-ebrahimi** [comment]
- Yes, I am using v0.1.6
- Here is my code, running in initState:

      player = Player(id: 69420);
      player.playbackStream.listen((PlaybackState state) {
        playbackState = state;
      });
      player.positionStream.listen((PositionState state) {
        positionState = state;
      });
      Media media = Media.network(widget.video.url);
      D("media added");
      player.open(media, autoStart: true);
      D("media opened");

**Comment by alexmercerind** [comment]
![stack](https://user-images.githubusercontent.com/28951144/130741567-42cb7a66-cc01-4509-a8c1-00c7204b42df.png)
I tried opening 2 `Media` in a `Playlist` in `--release` mode & exception seems to happen in Flutter's shared library itself, not sure of the cause yet.

**Comment by alexmercerind** [comment]
Found the cause. Fixing in #135. Will update on pub.dev once fixed.

**Comment by sunjhtrustmobi** [comment]
@alexmercerind Thank you so much for such a quick fix! It solves a big problem for me. 🙏🙏🙏
