### ISSUE TITLE
crashing in Profile and Release mode windows

### ISSUE THREAD

**Issue by sanalkv** [alexmercerind/dart_vlc#136]
Works fine in debug.

`[   +9 ms] Lost connection to device.
[  +31 ms] "flutter run" took 84,309ms.
[ +201 ms] ensureAnalyticsSent: 174ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0`

**Comment by sanalkv** [comment]
I believe this has been already reported. #124

**Comment by alexmercerind** [comment]
@sanalkv on macOS, you may temporarily apply these changes: https://github.com/alexmercerind/dart_vlc/commit/ee41049152a8ab2164fe92db0ab1562d0a4f3970 & crash won't happen.

I will publish next version on pub.dev with same changes after another bug (for Windows only) is fixed. Thankyou.

**Comment by sanalkv** [comment]
Sure, thanks for this wonderful package.
