### ISSUE TITLE
Linux CMake 3.13 or higher is required.  You are running version 3.10.2

### ISSUE THREAD

**Issue by dumabg** [alexmercerind/dart_vlc#146]
When I try to use the component in Flutter 2.2.1, Dart 2.13.1, it gives the error:

CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:9 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.10.

and the build fails.

**Comment by alexmercerind** [comment]
Please change the CMake version in this line to `3.10` on your local files. I cannot publish a new version. I assume you are using snap version of Flutter.

https://github.com/alexmercerind/dart_vlc/blob/022871d0d93bb9ee15d435e45b84ad87c2e1e0ac/linux/CMakeLists.txt#L9

**Comment by dumabg** [comment]
Yes, I'm using snap version of Flutter.
I've changed:
-  /home/XXXX/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.7/dartvlc/CMakeLists.txt
- /home/XXXX/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.7/linux/CMakeLists.txt

Then gives this error:

CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/CMakeLists.txt:50 (list):
  list does not recognize sub-command TRANSFORM                         
                                                                                                                                               
CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:46 (target_link_options):
  Unknown CMake command "target_link_options".

**Comment by jnschulze** [comment]
List transformations were introduced with CMake 3.12 and `target_link_options` was added in CMake 3.13.
Looks like you need to update CMake...

**Comment by dumabg** [comment]
I haven't Cmake on my system. It's using the snap Flutter Cmake .

**Comment by jnschulze** [comment]
The Flutter snap got migrated from the `core18` image to `core20` in April (see https://github.com/canonical/flutter-snap/commit/e339663e880e489d7db3c5360436702e5c517056). However, it has been reverted back to `core18`. So why don't you get in touch with the maintainers of the Flutter snap and ask why they stick to an old base image.

**Comment by krjw-eyev** [comment]
@dumabg I am going to close this since I don't think it has anything to do with this project. I am sorry you need to update cmake.
