### ISSUE TITLE
Crash when disposing Video

### ISSUE THREAD

**Issue by krjw-eyev** [alexmercerind/dart_vlc#148]
I get a crash when disposing a `Video` too quickly.

This seems to happen because the `StreamController` in `_VideoStateFallback` cannot be closed (the Future does not resolve) in the `dispose()` method and therefore `super.dispose()` is never called.

Fix is not awaiting `videoStreamControllers[playerId]?.close();` in `_VideoStateFallback.dispose()`.

**Comment by RegNex** [comment]
Please, when will this update be available?
