### ISSUE TITLE
When using git in pubspec building failed because the submodules are not pulled.

### ISSUE THREAD

**Issue by krjw-eyev** [alexmercerind/dart_vlc#150]
I have experimented with using git in pubspec for this repo. And to make it work there need to be made some changes:

In the top pubspec.yaml use this for dart_vlc_ffi

```yaml
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc
      path: ./ffi
```

In both the macOS and iOS dart_vlc.pubspec add this script as the first one.

```ruby
s.script_phases = [
{
  :name => 'Fetch submodules... only needed if using git in pubspec.yaml',
  :show_env_vars_in_log => true,
  :script => 'cd ${PODS_TARGET_SRCROOT}/.. && git submodule update --init --recursive',
  :execution_position => :before_compile
},
...
```

This could be more of a documentation. I would have made a pull request but I would like to hear your thoughts first.

Also I have noticed that [dart-lang/pub#2807](https://github.com/dart-lang/pub/issues/2807#issue-769279139) proposes support for submodules. This could be the solution if they implement it.

**Comment by hasnainelahi** [comment]
s.script_phases = [
{
  :name => 'Fetch submodules... only needed if using git in pubspec.yaml',
  :show_env_vars_in_log => true,
  :script => 'cd ${PODS_TARGET_SRCROOT}/.. && git submodule update --init --recursive',
  :execution_position => :before_compile
},
<img width="835" alt="image" src="https://user-images.githubusercontent.com/44682591/160266629-ad492917-8d46-4ba7-bc76-37665f3385bc.png">
this script already available in my case and still getting this error
Launching lib/main.dart on macOS in debug mode... lib/main.dart:1 Command CompileSwift failed with a nonzero exit code Command CompileSwift failed with a nonzero exit code CMake Error: The source directory "/Users/Mac15/Documents/Flutter Projects/sample flutter projects/sample_project/macos/Pods/projects/sample_project/macos/Flutter/ephemeral/.symlinks/plugins/dart_vlc/macos/deps" does not exist. Specify --help for usage, or press the help button on the CMake GUI. Command PhaseScriptExecution failed with a nonzero exit code Command CompileSwift failed with a nonzero exit code note: Using new build system note: Building targets in parallel note: Planning build note: Analyzing workspace note: Constructing build description note: Build preparation complete ** BUILD FAILED **

**Comment by GroovinChip** [comment]
@hasnainelahi try regenerating your `macos` runner
