### ISSUE TITLE
Media media = Media.file(File(path), parse: true) or media.parse(xxx)  not work in flutter 2.5

### ISSUE THREAD

**Issue by j787701730** [alexmercerind/dart_vlc#155]
```
String getDuration(path) {
    String duration = '--:--';
    try {
      Media media = Media.file(File(path), parse: true);
      print(media);
      // media.parse(Duration.zero);
      if (media.metas['duration'] != null) {
        Duration d = Duration(milliseconds: int.tryParse('${media.metas['duration']}')!);
        duration =
            '${d.inMinutes.toString().padLeft(2, '0')}:${(d.inSeconds - d.inMinutes * 60).toString().padLeft(2, '0')}';
      }
    } catch (d) {
      print("error");
      return duration;
    }
    return duration;
  }

```
D:\code\music_windows_flutter>flutter doctor -v
[√] Flutter (Channel beta, 2.5.0, on Microsoft Windows [Version 10.0.19043.1165], locale zh-CN)
    • Flutter version 2.5.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at C:/AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:/AndroidStudio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\aoc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 1 category.

**Comment by krjw-eyev** [comment]
Can I assume you are building for Windows? What exactly is the problem?

**Comment by j787701730** [comment]
yes , build Windows. It can be read before the flutter 2.5, 
![image](https://user-images.githubusercontent.com/23625690/133174409-83812051-d85f-482a-9604-2fcc63135277.png)
, but flutter 2.5 function getDuration not work.

**Comment by j787701730** [comment]
![image](https://user-images.githubusercontent.com/23625690/133175102-eb84cb07-9cfe-4532-9991-e2798596d620.png)

**Comment by j787701730** [comment]
![image](https://user-images.githubusercontent.com/23625690/133175311-1e9aeb11-604f-4a12-8197-4d3019c714fc.png)
![image](https://user-images.githubusercontent.com/23625690/133175336-42e4aa80-f04e-4b50-92e7-bc1e450d5c99.png)
