### ISSUE TITLE
Unhandled Exception: Unsupported operation: Cannot set value in unmodifiable Map

### ISSUE THREAD

**Issue by Martini765** [alexmercerind/dart_vlc#158]
Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Manjaro Linux 5.4.143-1-MANJARO, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

Parsing a media causes a Unhandled Exception:
`File file = File.fromUri(uri)`;
`final media = Media.file(file, parse: true, timeout: Duration(seconds: 5));`

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: Cannot set value in unmodifiable Map`
`#0      _ImmutableMap.[]= (dart:core-patch/immutable_map.dart:74:5)`
`#1      Media.parse (package:dart_vlc_ffi/src/mediaSource/media.dart:111:15)`
`#2      Media.file (package:dart_vlc_ffi/src/mediaSource/media.dart:46:13)`

This is likely the cause:
`const Media._(
      {required this.mediaType, required this.resource, this.metas = const {}});`

It iniatilize **metas** with a constant,  immutable map
A possible solution is to pass a empty non-constant map to the constructor:
`final media = Media._(mediaType: MediaType.file, resource: file.path, metas: {});`

**Comment by alexmercerind** [comment]
Let's target this at #155. 

Thanks for the report.
