### ISSUE TITLE
error when loading

### ISSUE THREAD

**Issue by zezo357** [alexmercerind/dart_vlc#165]
when the network loading is an error for any reason is there is something to listen to let the user that an error happened?

**Comment by alexmercerind** [comment]
Added new `errorStream` attribute to `Player` class to listen to error events, but `libvlc_errmsg` seems to always be `NULL`. Anyway, it gets invoked when something wrong happens. 

https://github.com/alexmercerind/dart_vlc/blob/1f9243cd7715309bf24f86f49ed9766846473c10/example/lib/main.dart#L60-L62

I know it's been too long.
