### ISSUE TITLE
vlcpp/vlc.hpp & dart_api_dl.h not found

### ISSUE THREAD

**Issue by arsabe75** [alexmercerind/dart_vlc#182]
When I try to build example I get these errors.

'vlcpp/vlc.hpp': No such file or directory

'dart_api_dl.h': No such file or directory

**Comment by jiahaoChen** [comment]
Hi,
did you fetch the submodule?
FYR
[fetch submodule](https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules)
[other issues](https://github.com/alexmercerind/dart_vlc/issues/145)
