### ISSUE TITLE
setVolume() affects all players

### ISSUE THREAD

**Issue by KyleKun** [alexmercerind/dart_vlc#183]
Hi @alexmercerind, first of all, thanks for your great work!

I am making a game where I need to have separate players, one for bgm and the other for sfx.

``` dart
static Player vlcBgmPlayer = Player(
    id: 69,
    commandlineArguments: ['--no-video'],
  );

static Player vlcSfxPlayer = Player(
    id: 420,
    commandlineArguments: ['--no-video'],
  );
```

The problem is, if you use `setVolume()` in one of them, the other one will also apply the volume change. (The case is, I would like to keep the vlcBgmPlayer  in max volume and play an audio with vlcSfxPlayer  in a lower volume, so I call `vlcSfxPlayer.setVolume()` before playing the audio but then the vlcBgmPlayer is also affected).

I'm not sure if I am doing something wrong, please enlighten me if so...
Thank you!

**Comment by KyleKun** [comment]
Ah, missed this one https://github.com/alexmercerind/dart_vlc/issues/90.
Closing as duplicate.

**Comment by alexmercerind** [comment]
@KyleKun thanks for the report. I'll have a look.
