### ISSUE TITLE
[only-video] High CPU Usage (in Windows)

### ISSUE THREAD

**Issue by zyrouge** [alexmercerind/dart_vlc#184]
Running even the simple example app seems to cause high CPU usage and very high power usage.

When playing:
![image](https://user-images.githubusercontent.com/50770114/140503592-af186c04-8b39-4ecd-848a-65d212025240.png)

When paused:
![image](https://user-images.githubusercontent.com/50770114/140503660-21014ed8-9592-485d-9567-e8278ec08d9c.png)

## Comparing to VLC:
When playing:
![image](https://user-images.githubusercontent.com/50770114/140503802-2ac9bc9d-ef6d-4436-b6e6-917b620634df.png)

## Comparing to MPV:
When playing:
![image](https://user-images.githubusercontent.com/50770114/140504163-9d8afc53-56ec-493f-9ff4-b164d1165986.png)

Honestly the usages of vlc and the app is very similar when considering only the player but an average should not use this much of resources for just video playback. Comparatively MPV seems to use very less amount of resources. The gap between 8% / 22% and 42% is just too much. My average app seems to use nearly 62% CPU which is just too much when someone is multitasking.

**Comment by alexmercerind** [comment]
There are certain reasons why it can't be improved as of now (sorry for long explanation):

Currently stable VLC / libVLC 3.x.x has no API to render video to custom viewport other than `libvlc_video_set_callbacks`. This essentially copies the video frame buffer to RAM & is quite CPU intensive operation to be performed each frame (which I then pass to flutter's texture registrar API as "pixel buffer" on all Windows, Linux & MacOS). The load of these video callbacks, thus reflects in the CPU usage of the application. So, in summary there is no way to avoid this extra computation. 
From libVLC 4.0.0, we will get zero-copy (all GPU accelerated) API to render video using OpenGL (however I have no knowledge of OpenGL yet). Even then, Flutter doesn't have OpenGL texture type for Windows (yet) (only pixel buffer texture & still unmerged Direct3D texture https://github.com/flutter/engine/pull/26840). On Linux however, Flutter seem to have OpenGL based texture type along with pixel buffer one. 

What I can be done:
Use `libvlc_media_player_set_hwnd` to show video output. But, it completely overlaps the window content & only video will be visible (not very Flutter/Widget way of showing things).


With all that being said, my device has Ryzen 3 2200U & doesn't seem to have much trouble with 720p & 25 FPS videos. 1080p >= & higher frame rates definitely give my CPU a trouble however.

**Comment by alexmercerind** [comment]
![Screenshot 2021-11-05 172517](https://user-images.githubusercontent.com/28951144/140508949-59bb2f5e-37a0-436b-80ad-78d9a910bf4f.png)
My screenshot for reference.

**Comment by zezo357** [comment]
> Running even the simple example app seems to cause high CPU usage and very high power usage.
> 
> When playing: ![image](https://user-images.githubusercontent.com/50770114/140503592-af186c04-8b39-4ecd-848a-65d212025240.png)
> 
> When paused: ![image](https://user-images.githubusercontent.com/50770114/140503660-21014ed8-9592-485d-9567-e8278ec08d9c.png)
> 
> ## Comparing to VLC:
> When playing: ![image](https://user-images.githubusercontent.com/50770114/140503802-2ac9bc9d-ef6d-4436-b6e6-917b620634df.png)
> 
> ## Comparing to MPV:
> When playing: ![image](https://user-images.githubusercontent.com/50770114/140504163-9d8afc53-56ec-493f-9ff4-b164d1165986.png)
> 
> Honestly the usages of vlc and the app is very similar when considering only the player but an average should not use this much of resources for just video playback. Comparatively MPV seems to use very less amount of resources. The gap between 8% / 22% and 42% is just too much. My average app seems to use nearly 62% CPU which is just too much when someone is multitasking.

i think maybe its a problem related to flutter i had that problem too and fixed it and my cpu usage is 7% when paused 15% when playing 

for me the problem i was using old windows files from flutter the fix is 
1.delete windows folder from your flutter project
2.run this command inside your flutter project `flutter create --platforms=windows .`
now windows files will be updated to last version and cpu usage is less

**Comment by alexmercerind** [comment]
> > Running even the simple example app seems to cause high CPU usage and very high power usage.
> > When playing: ![image](https://user-images.githubusercontent.com/50770114/140503592-af186c04-8b39-4ecd-848a-65d212025240.png)
> > When paused: ![image](https://user-images.githubusercontent.com/50770114/140503660-21014ed8-9592-485d-9567-e8278ec08d9c.png)
> > ## Comparing to VLC:
> > When playing: ![image](https://user-images.githubusercontent.com/50770114/140503802-2ac9bc9d-ef6d-4436-b6e6-917b620634df.png)
> > ## Comparing to MPV:
> > When playing: ![image](https://user-images.githubusercontent.com/50770114/140504163-9d8afc53-56ec-493f-9ff4-b164d1165986.png)
> > Honestly the usages of vlc and the app is very similar when considering only the player but an average should not use this much of resources for just video playback. Comparatively MPV seems to use very less amount of resources. The gap between 8% / 22% and 42% is just too much. My average app seems to use nearly 62% CPU which is just too much when someone is multitasking.
> 
> i think maybe its a problem related to flutter i had that problem too and fixed it and my cpu usage is 7% when paused 15% when playing
> 
> for me the problem i was using old windows files from flutter the fix is 1.delete windows folder from your flutter project 2.run this command inside your flutter project `flutter create --platforms=windows .` now windows files will be updated to last version and cpu usage is less

I believe that `run_loop.cpp` template is no longer the issue on Windows. They updated the project template a while ago.

**Comment by zezo357** [comment]
> > > Running even the simple example app seems to cause high CPU usage and very high power usage.
> > > When playing: ![image](https://user-images.githubusercontent.com/50770114/140503592-af186c04-8b39-4ecd-848a-65d212025240.png)
> > > When paused: ![image](https://user-images.githubusercontent.com/50770114/140503660-21014ed8-9592-485d-9567-e8278ec08d9c.png)
> > > ## Comparing to VLC:
> > > When playing: ![image](https://user-images.githubusercontent.com/50770114/140503802-2ac9bc9d-ef6d-4436-b6e6-917b620634df.png)
> > > ## Comparing to MPV:
> > > When playing: ![image](https://user-images.githubusercontent.com/50770114/140504163-9d8afc53-56ec-493f-9ff4-b164d1165986.png)
> > > Honestly the usages of vlc and the app is very similar when considering only the player but an average should not use this much of resources for just video playback. Comparatively MPV seems to use very less amount of resources. The gap between 8% / 22% and 42% is just too much. My average app seems to use nearly 62% CPU which is just too much when someone is multitasking.
> > 
> > i think maybe its a problem related to flutter i had that problem too and fixed it and my cpu usage is 7% when paused 15% when playing
> > 
> > for me the problem i was using old windows files from flutter the fix is 1.delete windows folder from your flutter project 2.run this command inside your flutter project `flutter create --platforms=windows .` now windows files will be updated to last version and cpu usage is less
> 
> I believe that `run_loop.cpp` template is no longer the issue on Windows. They updated the project template a while ago.

Yes they updated it, but the flutter windows project files don't get updated unless you delete them and do it again.

At least that was the problem in my case

**Comment by zyrouge** [comment]
> > > > Running even the simple example app seems to cause high CPU usage and very high power usage.
> > > > When playing: ![image](https://user-images.githubusercontent.com/50770114/140503592-af186c04-8b39-4ecd-848a-65d212025240.png)
> > > > When paused: ![image](https://user-images.githubusercontent.com/50770114/140503660-21014ed8-9592-485d-9567-e8278ec08d9c.png)
> > > > ## Comparing to VLC:
> > > > When playing: ![image](https://user-images.githubusercontent.com/50770114/140503802-2ac9bc9d-ef6d-4436-b6e6-917b620634df.png)
> > > > ## Comparing to MPV:
> > > > When playing: ![image](https://user-images.githubusercontent.com/50770114/140504163-9d8afc53-56ec-493f-9ff4-b164d1165986.png)
> > > > Honestly the usages of vlc and the app is very similar when considering only the player but an average should not use this much of resources for just video playback. Comparatively MPV seems to use very less amount of resources. The gap between 8% / 22% and 42% is just too much. My average app seems to use nearly 62% CPU which is just too much when someone is multitasking.
> > > 
> > > 
> > > i think maybe its a problem related to flutter i had that problem too and fixed it and my cpu usage is 7% when paused 15% when playing
> > > for me the problem i was using old windows files from flutter the fix is 1.delete windows folder from your flutter project 2.run this command inside your flutter project `flutter create --platforms=windows .` now windows files will be updated to last version and cpu usage is less
> > 
> > 
> > I believe that `run_loop.cpp` template is no longer the issue on Windows. They updated the project template a while ago.
> 
> Yes they updated it, but the flutter windows project files don't get updated unless you delete them and do it again.
> 
> At least that was the problem in my case

Pretty sure my template is up-to-date. (https://github.com/yukino-app/yukino)

**Comment by alexmercerind** [comment]
So I finally have an update. I have started working on: [flutter_native_view](https://github.com/alexmercerind/flutter_native_view).

The setup can embed any random window inside Flutter just like a `Widget` very easily. I will build a new video player using UWP technologies and improve `dart_vlc`. Performance is 100% native.

**Comment by fischerscode** [comment]
@alexmercerind 
Nice, good luck and thank you for your work. 👍

**Comment by danw8989** [comment]
> So I finally have an update. I have started working on: [flutter_native_view](https://github.com/alexmercerind/flutter_native_view).
> 
> The setup can embed any random window inside Flutter just like a `Widget` very easily. I will build a new video player using UWP technologies and improve `dart_vlc`. Performance is 100% native.

You are a godsend, man. Keep up with the good work

**Comment by GroovinChip** [comment]
> So I finally have an update. I have started working on: [flutter_native_view](https://github.com/alexmercerind/flutter_native_view).
> 
> The setup can embed any random window inside Flutter just like a `Widget` very easily. I will build a new video player using UWP technologies and improve `dart_vlc`. Performance is 100% native.

Damn, yo. That sounds amazing. How exactly would you use this in the context of VLC? Would you embed the actual VLC application?

**Comment by alexmercerind** [comment]
@danw8989,
> Any plany to enmbed in linux native view?

There's already an unmerged pull request for platform view support on Linux. Even Windows support is a bit of work in progress, but video playback is working good anyway.
I could start experimenting on my own implementation but I don't really have reasons personally. I've not been much active on `dart_vlc` either lately (I will return soon possibly).

 @GroovinChip 

> How exactly would you use this in the context of VLC?

The default libVLC behaviour is to launch a new video output window when a video is opened. One of early days implementation of `dart_vlc` screenshot (when I didn't implement texture callbacks):
![20220330_004349.jpg](https://user-images.githubusercontent.com/28951144/160689926-0c7fa658-f3ca-4075-a990-4469f21338fc.jpg)

So idea in general (and it's possible as of now, no experiment or research needed) can be one of the two:
- Embed that VLC window (which you can see has no obstructing controls or buttons, just the video) directly, keeping our Flutter controls/widgets. 
- libVLC API also allows to render video output directly onto a separate window (filling whole area). So, launching a new window, rendering libVLC video output on it & embedding it.

As for the "UWP technologies" I said in above comment, it's possible using XAML islands. See below.
A project I made (now deprecated):

This video is completely rendered using modern Windows 10 APIs (as used in UWP apps or official Movies & TV app from Microsoft) and doesn't require bundling ton of libVLC DLLs. ~200 kB size increase compared to ~150 MB in dart_vlc Windows. So, this can also be embedded.

![screenshot.jpg](https://user-images.githubusercontent.com/28951144/160690728-3ab062a9-6cf3-4181-bf1d-8f4c1829f437.jpg)

That's all in summary.

**Comment by GroovinChip** [comment]
Amazing!

**Comment by alexmercerind** [comment]
So I've made a new video widget `NativeVideo` (try running example app in [native-video-impl](https://github.com/alexmercerind/dart_vlc/tree/native-video-impl) branch).

1080p, 30FPS, Ryzen 3 2200U (outdated ZEN I CPU).

https://user-images.githubusercontent.com/28951144/162067753-f59b04e2-019c-4dfc-90e7-6bb5b7222e69.mp4

It's powered entirely by [flutter_native_view](https://github.com/alexmercerind/flutter_native_view) & doesn't use Flutter's texture APIs at-all. The VLC video output is natively embedded.
There are few bugs in the implementation.

**Comment by alexmercerind** [comment]
EDIT: Old video was showing an MKV file, which consumes more CPU. Here's an MP4 file that takes 5-10% CPU only now.

So I've made a new video widget `NativeVideo` (try running example app in [native-video-impl](https://github.com/alexmercerind/dart_vlc/tree/native-video-impl) branch, Windows-only).

1080p, 30FPS, Ryzen 3 2200U (outdated ZEN I CPU). In general CPU usage should be 5-15%, I don't know why it's still kinda high.


https://user-images.githubusercontent.com/28951144/162072669-c062ed2a-bbff-4f41-a0c0-8fd4cd64a385.mp4


It's powered entirely by [flutter_native_view](https://github.com/alexmercerind/flutter_native_view) & doesn't use Flutter's texture APIs at-all. The VLC video output is natively embedded.
There are few bugs in the implementation.


But still, 5-10% is better than previous 40-50% CPU usage.

**Comment by alexmercerind** [comment]
Added: [NativeVideo docs](https://github.com/alexmercerind/dart_vlc#nativevideo)

Thanks!
Available on git repository (not pub.dev yet).
