### ISSUE TITLE
Listen to errors

### ISSUE THREAD

**Issue by zyrouge** [alexmercerind/dart_vlc#185]
The `Player` does not seem to throw any error when something unusual occurs. (Like invalid URL, infinite loading/buffering when the player fails to play a URL) So a stream where we the errors will be reported will be useful. This might be a duplicate of #165 but I just opened this to make it clear.

**Comment by DomingoMG** [comment]
Let's say you will execute the onError event in case of a player error, but we wouldn't know exactly the error, would we?

It's still interesting at least something was wrong, I'm going to try it, Good job @alexmercerind!

**Comment by alexmercerind** [comment]
> Let's say you will execute the onError event in case of a player error, but we wouldn't know exactly the error, would we? It's interesting, I'm going to give it a try, Good job Alex!

Yeah! `libvlc_errmsg` is always returning `NULL` for some reason. Let's see how stable things are.
