### ISSUE TITLE
Can't play network video on Windows

### ISSUE THREAD

**Issue by thegrxp** [alexmercerind/dart_vlc#187]
Everything works fine on MacOS. 
On Windows I can play File and Assets videos without trouble but I can't play a video from the network. It seems that nothing is loading. Unfortunatelly I don't have any log. Any idea?

Thank you for this amazing lib!

**Comment by alexmercerind** [comment]
Can you share URL or some logs? Are you able to access media over some web browser etc. ? You can try passing `commandlineArguments` as `['--log-verbose=3']` to enable detailed logging.

**Comment by thegrxp** [comment]
Oh thank you for the info about the command line! It appears the issue is on my server side. Sorry for the inconvenience.
