### ISSUE TITLE
main filter error: Failed to create video converter

### ISSUE THREAD

**Issue by tomassasovsky** [alexmercerind/dart_vlc#19]
Everything works just fine, but when i add and then open a media file (.mkv) i get this error:
```
[00007fd28c0021a0] main filter error: Failed to create video converter
```

**Comment by k1ycee** [comment]
I am thinking that the vlc engine does not process .mkv files naturally.

**Comment by alexmercerind** [comment]
It's not related to the project, but the selection of VLC plugins that you have on your PC.
