### ISSUE TITLE
Flutter - How to chromecast a camera view or agora stream via chromecast ?

### ISSUE THREAD

**Issue by fldvlpr** [alexmercerind/dart_vlc#198]
Hello @alexmercerind @jnschulze @stonega @mfkl @t1ooo @zanderso 

I was working on agora stream and what i want to achieve is i want to Chromecast agora stream.

So, I'm not to able to find methods or way to achieve this package via flutter_cast.

Let me know if there is a way to do so or this package supports this feature or not?

Thanks

**Comment by mfkl** [comment]
Hi,

Please don't ping people unnecessarily.

**Comment by alexmercerind** [comment]
@fldvlpr closing as this is a question about VLC usage, rather than a [dart_vlc](https://github.com/alexmercerind/dart_vlc) bug or feature-request.
