### ISSUE TITLE
Manjaro: Missing '/usr/lib/x86_64-linux-gnu/libvlc.so'

### ISSUE THREAD

**Issue by Yesterday17** [alexmercerind/dart_vlc#2]
My `libvlc.so` is located in `/usr/lib` directly without the sub direcotory.

![image](https://user-images.githubusercontent.com/8667822/111957412-f0ce4480-8b26-11eb-8bad-b1e0a6dd6931.png)

## System info
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 15.5 GiB of RAM
Graphics Processor: GeForce GTX 1070 with Max-Q Design/PCIe/SSE2

**Comment by alexmercerind** [comment]
Hi there @Yesterday17 !

I can't really say about this one, since I used this plugin on Ubuntu Linux.
And in my case when I installed libVLC using the apt command, the shared libraries were present under the directory.
This [stackexchange](https://unix.stackexchange.com/questions/586792/difference-between-usr-lib-and-usr-lib-x86-64-linux-gnu-folders) forum speaks a little about this.
I cannot say anything about it, as I have never used Manjaro or Arch. It is an issue with shared libraries, so make sure those are discoverable by Flutter engine.

Thanks.

**Comment by alexmercerind** [comment]
I'm trying to find how that goes for Arch. Let us know, if you find a solution for this category of distro.

**Comment by Yesterday17** [comment]
Maybe you can try [this](https://wiki.debian.org/Multiarch/Implementation#CMake).

On my laptop, `CMAKE_INSTALL_LIBDIR` is `lib`, so I guess it would be `lib/x86_64-linux-gnu` on ubuntu?

I tested it with the following `CMakeList.txt`:
```cmake
project(test)
include(GNUInstallDirs)
message(STATUS ${CMAKE_INSTALL_LIBDIR})
```

**Comment by alexmercerind** [comment]
@Yesterday17, were you able to get it working on your Manjaro?

**Comment by Yesterday17** [comment]
I made the following patch:

```cmake
include(GNUInstallDirs)
target_link_libraries(${PLUGIN_NAME} PRIVATE
  flutter
  PkgConfig::GTK
  "/usr/${CMAKE_INSTALL_LIBDIR}/libvlc.so"
)
```
On my laptop, `CMAKE_INSTALL_LIBDIR` is `lib`, so this patch works for me.

**Comment by alexmercerind** [comment]
@Yesterday17 ,
may you please make a pull request with the same. 🙂

**Comment by Yesterday17** [comment]
> @Yesterday17 ,
> may you please make a pull request with the same.

I've not tested on other distributions because I don't have much free space on my laptop. I can make a pull request, but further tests are needed.

**Comment by alexmercerind** [comment]
@Yesterday17 . Thankyou I'll test it.

**Comment by lycstar** [comment]
Yes, libvlc.so is in usr/lib/ in archlinux

**Comment by stonega** [comment]
I have the same issue on Fedora, and the libvlc.so.5 is in /usr/lib64/

**Comment by alexmercerind** [comment]
@stonega you may change the location inside `CMakeLists.txt` for the time being.

**Comment by stonega** [comment]
> @stonega you may change the location inside `CMakeLists.txt` for the time being.
Yes, I have changed it, and everything works as expected 😃

**Comment by alexmercerind** [comment]
Simply having `-lvlc` as clang flag actually works fine. So, I've completely removed the file path and replaced it with just `vlc`. Should work fine for all Linux breeds.
