### ISSUE TITLE
in IOS;No implementation found for method PlayerRegisterTexture on channel dart_vlc

### ISSUE THREAD

**Issue by C-Kristal** [alexmercerind/dart_vlc#203]
when play Video , throw error ↓ ,but it can only  play the sound of the video, and the video area is black. 

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method PlayerRegisterTexture on channel dart_vlc)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      new Player.<anonymous closure> (package:dart_vlc/dart_vlc.dart:61:25)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method PlayerUnregisterTexture on channel dart_vlc)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      Player.dispose (package:dart_vlc/dart_vlc.dart:67:5)
<asynchronous suspension>

**Comment by alexmercerind** [comment]
There is no texture implementation for iOS. I haven't implemented.
