### ISSUE TITLE
ios issue

### ISSUE THREAD

**Issue by amee13bit** [alexmercerind/dart_vlc#204]
fatal: not a git repository (or any of the parent directories): .git
Command PhaseScriptExecution failed with a nonzero exit code

pub version - 0.02
xcode 13

**Comment by virskor** [comment]
same and macos 
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:0912D21C-0F26-5BA6-BC61-3745C1AF08B6 }
{ platform:macOS, name:Any Mac }
fatal: not a git repository (or any of the parent directories): .git
Command PhaseScriptExecution failed with a nonzero exit code
Command CompileSwiftSources failed with a nonzero exit code
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in dependency order
** BUILD FAILED **
```

**Comment by winterdl** [comment]
fatal: not a git repository (or any parent up to mount point /Volumes)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Command PhaseScriptExecution failed with a nonzero exit code

I installed flutter by fvm, not using default install location

**Comment by virskor** [comment]
i am using fvm too, but i do not know a method to resolve this problem, can anyone give me a example to complete it. thanks

**Comment by alexmercerind** [comment]
I haven't tested iOS or macOS personally, I don't have a mac setup to test it myself. Feel free to raise a PR.

**Comment by alexmercerind** [comment]
No iOS support for now. macOS should be fixed.
