### ISSUE TITLE
Linux video work with free window

### ISSUE THREAD

**Issue by TechComet** [alexmercerind/dart_vlc#209]
Hi,

I try example .. video work with free window

need play video in embedded window inside my app

kubuntu 20.04
VLC media player 3.0.9.2 Vetinari

libvlc-dev 3.0.9.2-1 the newest version

**Comment by alexmercerind** [comment]
Are you playing HLS?

**Comment by TechComet** [comment]
yes

**Comment by alexmercerind** [comment]
I fixed this issue in d56e2438eee6258933effb2f29c4e74fa6f99365, I'm yet to update the pub.dev version. 

Could you make the changes locally for now?

Thanks.

**Comment by TechComet** [comment]
Im add this
```
dependencies:
  dart_vlc: ^0.1.8
```

same problem

**Comment by TechComet** [comment]
I now copy this file direct
`https://raw.githubusercontent.com/alexmercerind/dart_vlc/d56e2438eee6258933effb2f29c4e74fa6f99365/dartvlc/internal/events.h`

and replace with cache file
myproject_path/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/internal/events.h

it's work now

last your update not upload to pub.dev

**Comment by alexmercerind** [comment]
> I now copy this file direct `https://raw.githubusercontent.com/alexmercerind/dart_vlc/d56e2438eee6258933effb2f29c4e74fa6f99365/dartvlc/internal/events.h`
> 
> and replace with cache file myproject_path/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/internal/events.h
> 
> it's work now
> 

Yeah that's exactly what I meant by "Could you make the changes locally for now?".

I'll update `pub.dev` version soon & Git version of this repository won't work because I have submodules here.

**Comment by TechComet** [comment]
yes .. I can make the changes locally

Thank you
