### ISSUE TITLE
Loop media

### ISSUE THREAD

**Issue by jonatadashi** [alexmercerind/dart_vlc#21]
Hi,

first of thanks for the awesome package!

So, my problem is that I'm trying to loop a playlist.
I've tried [playlistMode](https://github.com/alexmercerind/dart_vlc/blob/14667ae8950e410d40c897e6c9daa2386bd6279d/lib/src/enums/playlistMode.dart#L7), but when i add `playlistMode: PlaylistMode.loop` it gives me `Undefined name 'PlaylistMode'`.

Would be great if you could look into it or have a solution.

**Comment by DomingoMG** [comment]
Hi @jonatadashi 
I'm going to check it, it may be that when merging it was not applied well.

Thanks for pointing out the problem.

**Comment by DomingoMG** [comment]
The changes are already fixed in this branch, I have not been able to test it in Linux because I do not have linux.

https://github.com/alexmercerind/dart_vlc/tree/playlistModeFixed

**Comment by jonatadashi** [comment]
Great, thanks for the quick response. But a few problems have arisen.

First, I'm now getting https://github.com/alexmercerind/dart_vlc/issues/13.
Second, where is https://github.com/alexmercerind/dart_vlc/blob/91e6addd6ab687e689b1f26ac92f98f9dfcd8c63/lib/dart_vlc.dart#L13 pointing at, since that file doesn't exist in src.

**Comment by alexmercerind** [comment]
@jonatadashi, #13 is due to GitHub being inaccessible by CMake for developers in China. I'm looking forward to create a `git submodule` instead.

**Comment by alexmercerind** [comment]
Let me have a look over the things & review everything.
Recording is a proposed feature by @DomingoMG. The branch was still WIP.

**Comment by jonatadashi** [comment]
> @jonatadashi, #13 is due to GitHub being inaccessible by CMake for developers in China. I'm looking forward to create a `git submodule` instead.

I'm not in China, so no idea how that happened. If I revert back to 0.0.5 it works.

**Comment by alexmercerind** [comment]
> I'm not in China, so no idea how that happened. If I revert back to 0.0.5 it works.

Sure. I'll take look at this issue in separate branch, please stay on stable 0.0.5 till then.

**Comment by DomingoMG** [comment]
@alexmercerind  @jonatadashi 
Oops, record.dart has escaped me, I'll update the branch shortly by removing that line

I'm sorry for the mistakes 😅

**Comment by DomingoMG** [comment]
https://github.com/alexmercerind/dart_vlc/tree/playlistModeFixed

The record.dart line is removed.
As I mentioned before, I am not 100% sure if the player.setPlaylistMode applies well on Linux, but on Windows it works perfectly.

**Comment by alexmercerind** [comment]
Should be fixed after latest commits.

**Comment by YukunXia** [comment]
Testing setting the playlist mode in Linux, but it seems that all three modes are the same, i.e. playing through the songs in the playlist one by one and stop. 

For example, whichever playlist mode is set in the example app at line 244 of `main.dart`, the player plays the songs one by one, and stops. What's more strange is that the first time a playlist is finished, the play/pause button will switch from pause to play, but for the later trials, that button will stay as pause at each end... If I click that pause, the playlist will be played from the first one again.

**Comment by YukunXia** [comment]
@alexmercerind https://github.com/alexmercerind/dart_vlc/blob/70c3b2b0f6162b93dda3915caba9cfd09111e0fc/ffi/native/dart_vlc.cpp#L158

Shouldn't the compared strings in line 158-167 be in CamelCase?

eg. "playlistMode.repeat" => "PlaylistMode.repeat"?

---

```dart
enum PlaylistMode {
	single,
	loop,
	repeat
}

void main() {
  PlaylistMode pm = PlaylistMode.loop;
  print("pm.toString() is ${pm.toString()}");
}
```
prints "pm.toString() is PlaylistMode.loop";

**Comment by alexmercerind** [comment]
Yeah @YukunXia you are right. There are many things that are currently missed by me since this FFI migration was done just yesterday. You may offer a PR if you wish.

**Comment by YukunXia** [comment]
> Yeah @YukunXia you are right. There are many things that are currently missed by me since this FFI migration was done just yesterday. You may offer a PR if you wish.

@alexmercerind The PR is there. However, even if I fixed the string problem, the play mode still behaves weirdly. For example, repeat mode will only play the same song twice. The loop mode seems to be the same as the single mode. Besides, the playing state stream oftentimes doesn't reflect the true one...
