### ISSUE TITLE
Custom Controls

### ISSUE THREAD

**Issue by AlexZorzi** [alexmercerind/dart_vlc#211]
is it possible to add some custom controls, maybe in the menu in the bottom right, it would be easier to exit the player if we want a page with only the player in fullscreen

**Comment by alexmercerind** [comment]
Use a `Stack` widget to add controls on top of `Video` widget and read streams in the `Player` to update? Pass `showControls` as `false` to disable default widgets.
I don't think I can provide any customisation within package other than just disabling it. In any production application, one would most likely create their own set of controls & not use the basic ones present in the package.
I had implemented full screen very well the other day in one of my apps.
