### ISSUE TITLE
How to generate dart_vlc.dll or dart_vlc.so

### ISSUE THREAD

**Issue by kiam123** [alexmercerind/dart_vlc#217]
I want to generate a dart_vlc.so or dart_vlc.dll and want to use in project [dart_vlc_ffi](https://pub.dev/packages/dart_vlc_ffi)

Can teach me how to generate? Thank you

**Comment by alexmercerind** [comment]
Hey! Think of `dart_vlc` shared library as a hook used to call functions from pre-compiled libVLC shared libraries.
When you build the application, it will be automatically generated in your build directory (it's configured that way) or you may compile yourself using CMake script or using command line.

**Comment by alexmercerind** [comment]
FYI, `dart_vlc_ffi` just contains FFI bindings to the shared library & there's almost zero point of using it alone (no shared library, no video output, just Dart mappings). The `dart_vlc` itself uses `dart_vlc_ffi` & ensures the building of shared library along handling the current implementation of video playback.
