### ISSUE TITLE
How to reduce the dll file?

### ISSUE THREAD

**Issue by itning** [alexmercerind/dart_vlc#220]
I used this project to build a music player (doesn't need to play video), the total dll file after packaging is 125 MB, so I would like to ask how to simplify the dll file, or which files can be removed?

![image](https://user-images.githubusercontent.com/19759891/156740277-f4c4bd80-76d8-444a-a767-c09d613ffc83.png)

**Comment by alexmercerind** [comment]
https://wiki.videolan.org/Win32Compile/
