### ISSUE TITLE
[proposal] Don't show "skip_previous" and "skip_next" buttons if there is only one `Media` to play

### ISSUE THREAD

**Issue by GroovinChip** [alexmercerind/dart_vlc#221]
Take the following sample code (lifted from my work to support desktop & web for stream_chat_flutter):

```dart
package.player.open(
  Playlist(
    medias: [
      Media.network(package.attachment.assetUrl),
    ],
  ),
  autoStart: widget.autoplayVideos,
);
```
A `Video` widget is slightly further down the widget tree.

This code produces a `Video` player with the standard controls, including the "skip_previous" and "skip_next" buttons - but there is only one `Media` to play.

I propose that in such a case these buttons should not be rendered.

This would probably necessitate something like the addition of a `queueLength` property to the `Video` and `Control` widgets, where the developer would pass the length of their `medias` list to `Video`, which would subsequently pass it to `Control`. `Control` would then show the relevant buttons if the value of `queueLength` is `> 1`, and not show them if the value is `<= 1`.

**Comment by alexmercerind** [comment]
Thanks for the feedback! I will take a look.
