### ISSUE TITLE
Video runs in debug and release mode, but windows build exe file doesn't

### ISSUE THREAD

**Issue by alt-Pranav** [alexmercerind/dart_vlc#222]
**I have built a video player app in Flutter for windows using the dart_vlc package.**
The app plays a video on loop when it starts and switches to different videos on different triggers.
When I run `flutter run -d windows` or `flutter run -d windows --release`  the app works perfectly.
The videos are added in the assets folder and the assets folder is added to the pubspec.yaml file as 
<pre>
assets:
    - assets/
</pre>
However, after I build the app for windows using `flutter build windows`, the .exe application generated in **build\windows\runner\Release** runs but the app window only shows a black screen. The black screen persists indefinitely and doesn't go away after some time.  The sound from the video is not played either.
The assets are visible in the build file as **build\windows\runner\Release\data\flutter_assets\assets** and I have used their relative path to load them in the code as `vlc_pkg.Media _media = vlc_pkg.Media.file(
    File('assets/xxx.mp4'),
  );`

I don't think this is a build error because running it in `--verbose` shows no errors. 
I don't know if this problem is because the assets aren't loading or if something else is the matter entirely.

When I run `flutter build windows` , this is my output:
>flutter build windows
Running "flutter pub get" in app_name...                           9.5s

 Building with sound null safety 
<pre color="red">
app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(153,13): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(153,13): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\api\api.cc(303,59): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\api\api.cc(324,51): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj] 
</pre>
Building Windows application...    

Please let me know if anyone has faced this problem and the solution to it!

**Comment by alt-Pranav** [comment]
Even though the flutter build shows those warnings, it compiles properly and so I haven't made any of the changes specified in the warning. Could those be the issue? But then why don't they occur with `flutter run -d windows` ??

**Comment by alexmercerind** [comment]
Invalid. Read [docs](https://github.com/alexmercerind/dart_vlc#create-a-media-for-playback) again.

**Comment by alt-Pranav** [comment]
Thanks for your response! I missed the `Media.assets('xxx.mp4');` in the docs and was using `Media.file()` incorrectly in its place, I noticed it after seeing your comment.
Just mentioning it here in case anyone makes the same mistake I did!
The app works fine now!

**Comment by waulite-786** [comment]
when i run from video code but when I create build blank screen showing nothing play 
while creating build error comming 

F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(470,59): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(491,51): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(502,57): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(503,46): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(503,59): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(509,72): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(510,46): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\api\api.cc(510,59): warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
F:\DesktopApp\wauly_signage\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\core\player\player.cc(327,9): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [F:\DesktopApp\wauly_signage\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]

**Comment by waulite-786** [comment]
> **I have built a video player app in Flutter for windows using the dart_vlc package.** The app plays a video on loop when it starts and switches to different videos on different triggers. When I run `flutter run -d windows` or `flutter run -d windows --release` the app works perfectly. The videos are added in the assets folder and the assets folder is added to the pubspec.yaml file as
> 
> assets:
>     - assets/
> However, after I build the app for windows using `flutter build windows`, the .exe application generated in **build\windows\runner\Release** runs but the app window only shows a black screen. The black screen persists indefinitely and doesn't go away after some time. The sound from the video is not played either. The assets are visible in the build file as **build\windows\runner\Release\data\flutter_assets\assets** and I have used their relative path to load them in the code as `vlc_pkg.Media _media = vlc_pkg.Media.file( File('assets/xxx.mp4'), );`
> 
> I don't think this is a build error because running it in `--verbose` shows no errors. I don't know if this problem is because the assets aren't loading or if something else is the matter entirely.
> 
> When I run `flutter build windows` , this is my output:
> 
> > flutter build windows
> > Running "flutter pub get" in app_name...                           9.5s
> 
> Building with sound null safety
> 
> app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(153,13): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
> app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(153,13): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
> app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\api\api.cc(303,59): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
> app_name\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\api\api.cc(324,51): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [app_name\build\windows\dart_vlc_core\dart_vlc_core.vcxproj] 
> Building Windows application...
> 
> Please let me know if anyone has faced this problem and the solution to it!



same issue please let me know
