### ISSUE TITLE
support for web

### ISSUE THREAD

**Issue by telostia** [alexmercerind/dart_vlc#224]
Hi, It would be cool to have support for web support. Since there's no support for web, I had to load another package called justaudio but... flutter won't let me compile at all even if I have platform specific conditions in the app. Is there a way to disable dart_vlc from compling when building for the web?

**Comment by telostia** [comment]
For those who came across this problem, there is a fix where you can abstract features based on platform here: https://gpalma.pt/blog/conditional-importing/.
I use vlc for windows and justaudio plugin for mobile/mac os platforms.

**Comment by alexmercerind** [comment]
Sorry I didn't see the question coming & yeah you need to use conditional imports. `dart:ffi` or `package:ffi` are not available for web & I don't plan to support web for now. See: https://github.com/alexmercerind/dart_vlc/issues/78

I've been working on improving video performances on desktop. FYI: https://github.com/alexmercerind/flutter_native_view
