### ISSUE TITLE
Can't run on Flutter 2.10.4

### ISSUE THREAD

**Issue by a-v-ebrahimi** [alexmercerind/dart_vlc#234]
**This is for running my app on macOS :**
 dart_vlc was compiling up to now, but after upgrading to Flutter 2.10.4 I receive this error while compiling:

```
[100%] Linking CXX static library libdart_vlc_core.a
[100%] Built target dart_vlc_core
Install the project...
-- Install configuration: ""
-- Installing: /Users/abd/gits/myflutter/macos/Pods/../Flutter/ephemeral/.symlinks/plugins/dart_vlc/macos/deps/lib/libdart_vlc_core.a
error: install_name_tool: can't open file: /Users/abd/gits/myflutter/macos/Pods/VLCKit/VLCKit.xcframework/macos-arm64_x86_64/VLCKit.framework/VLCKit (No such file or directory)

```

**Comment by a-v-ebrahimi** [comment]
@jnschulze @namniav
Gentlemen, do you have any idea?
Thanks.

**Comment by GroovinChip** [comment]
@a-v-ebrahimi you need to regenerate your `macos` runner

**Comment by a-v-ebrahimi** [comment]
Thanks, but how do I do that?

**Comment by alexmercerind** [comment]
> @jnschulze @namniav Gentlemen, do you have any idea? Thanks.

Please don't ping people unnecessarily.
It's generosity of open-source contributors that they publish their code / contribute online & provide free support too. 
Everyone is involved with their work-schedule & personal-life.
No one is getting any major profit by maintaining this.
People voluntary opt as "[watchers](https://github.com/alexmercerind/dart_vlc/watchers)" if they're interested to be part of conversation (even though that also doesn't mean they'll be sitting to reply at an issue thread after a ping).

> Thanks, but how do I do that?

Re-create the `macos` directory in your Flutter project. Run (after deleting `macos` folder):
```
flutter create --platforms macos .
```
A Google search would've been enough for this (though I don't think this is a very mind-blowing task for a Flutter developer anyway).

Thanks.
