### ISSUE TITLE
dart_vlc CMake issue on macos desktop

### ISSUE THREAD

**Issue by hasnainelahi** [alexmercerind/dart_vlc#236]
Issue: it working on windows. But Getting errors on macos desktop. I need this video player in macos. How can I solve it? kindly answer it, and give me a chance to say thanks  💓

Error:
Command CompileSwiftSources failed with a nonzero exit code
CMake Error: The source directory "[/Users/hasnainelahi/Desktop/Work]() Drive[/Lab/example/macos/Pods/Drive/Lab/example/macos/Flutter/ephemeral/.symlinks/plugins/dart_vlc/macos/deps]()" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in dependency order
** BUILD FAILED **

Exception: Build process failed
Exited (sigterm)

dependencies:
  dart_vlc: ^0.1.9
-----------------------
(cmake --version) CMake version: 3.22.3
-----------------------
(flutter --version) Flutter: 2.10.3 • channel stable 
-----------------------
Dart: 2.16.1
-----------------------

**Comment by alexmercerind** [comment]
Hello!
Apologies. Sad to say I don't own a macOS running device to solve this issue. You're own your own for this one. Sorry.

**Comment by a-v-ebrahimi** [comment]
Install CMake manually

**Comment by alexmercerind** [comment]
> Install CMake manually

Thanks for the reply @a-v-ebrahimi, if your issue is solved please consider closing #234.

**Comment by a-v-ebrahimi** [comment]
No, unfortunately #234 is not fixed by this solution.

**Comment by hasnainelahi** [comment]
Thanks for the reply @a-v-ebrahimi I already installed CMake manually. Is it working on your macos?

**Comment by GroovinChip** [comment]
@hasnainelahi try regenerating your `macos` runner

**Comment by alexmercerind** [comment]
Answered at #234.

**Comment by hasnainelahi** [comment]
Already did that but not working

**Comment by hasnainelahi** [comment]
@[alexmercerind](https://github.com/alexmercerind) you closed the issue but it is not solved. I also tried upgrading flutter, integrating it in new project, regenerating macos runner. flutter clean,  flutter pub upgrade. Still not working .... please help me out to solve it. or let me know any other package for macos to play video. 
Thank you

**Comment by hasnainelahi** [comment]
> @hasnainelahi try regenerating your `macos` runner   :    not solved.

**Comment by hasnainelahi** [comment]
It seems like some files and folders are missing
