### ISSUE TITLE
UDP stream on Windows opens in new window

### ISSUE THREAD

**Issue by ZoubairDaddow** [alexmercerind/dart_vlc#237]
When I try to open UDP link on Windows
The player open new window using DirectX

![image](https://user-images.githubusercontent.com/32312290/160272654-17e419a7-6076-4df6-9bbb-7001cbf28b6a.png)

**Comment by alexmercerind** [comment]
version?

**Comment by ZoubairDaddow** [comment]
`dart_vlc: ^0.1.8`

`[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1266], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.8) 
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability  `

**Comment by alexmercerind** [comment]
Update to v0.1.9. I had fixed this in d56e2438eee6258933effb2f29c4e74fa6f99365 & as already said at #201.
