### ISSUE TITLE
macos build dartvlc_core: No such file or directory

### ISSUE THREAD

**Issue by deanwang01** [alexmercerind/dart_vlc#239]
macos
dart_vlc: ^0.1.9

already installed cmake

Compilation error: make: *** dartvlc_core: No such file or directory. Stop.

**Comment by xiaodusx1** [comment]
brew install cmake
flutter clean
flutter pub get
pod install (if you want know more ,use --verbose)(fangqiang)

**Comment by alexmercerind** [comment]
> brew install cmake flutter clean flutter pub get pod install (if you want know more ,use --verbose)(fangqiang)

@xiaodusx1 is your issue fixed?

I don't have a mac, so I can't help. macOS support is community based, I only maintain Windows & Linux implementations. All three depend upon a common core.

**Comment by alexmercerind** [comment]
CI builds are not failing. Closing.
