### ISSUE TITLE
Bad performance in Windows 10

### ISSUE THREAD

**Issue by gkovac42** [alexmercerind/dart_vlc#243]
I'm working on a Flutter Windows application. When I'm trying to play multiple short audio files in a short succession the whole UI becomes very laggy and causes lag spikes. Sometimes the UI remains unresponsive until the sound playback finishes. Am I doing something wrong?

The code looks something like this:
```
// initilitzing the player
Player soundPlayer = Player(id: 0, commandlineArguments: ['--no-video']);

// method that plays a sound
void playSound(String sound) {
    soundPlayer?.open(Media.asset(sound), autoStart: true);
}
```

Steps to reproduce: call playSound() multiple times in short succession (i.e. on a button click).

Tested with:
```
flutter 2.10.4
dart_vlc: ^0.1.9
dart_vlc_ffi: ^0.1.5+1
windows 10
```

**Comment by alexmercerind** [comment]
#184. Duplicate.

Also don't include `dart_vlc_ffi` in your pubspec.yaml.

**Comment by alexmercerind** [comment]
Ah this is for audio playback (and not video). But sadly, I can't reproduce.

**Comment by alexmercerind** [comment]
You may consider sharing your code in a repo so that I can give my guidance or see the possible issues. I suspect you may be causing unnecessary rebuilds e.g. setState etc.

**Comment by gkovac42** [comment]
What I posted above is the whole code. I'm not calling setState and not rebuilding UI at all. Just calling the open() method on a button click quickly will cause the UI to freeze.

**Comment by alexmercerind** [comment]
> What I posted above is the whole code. I'm not calling setState and not rebuilding UI at all. Just calling the open() method on a button click quickly will cause the UI to freeze.

Man you can atleast try running the example app on the repository: https://github.com/alexmercerind/dart_vlc/blob/master/example/lib/main.dart.
It works great & doesn't lag at all.

**Comment by gkovac42** [comment]
I've just tried the example app and it indeed lags, and very much so.  I load an .mp3 file into the playlist and when clicking on the play button multiple times the UI becomes laggy and unresponsive. I can upload you a screen capture if you wish...

**Comment by alexmercerind** [comment]
@gkovac42 are you in release mode? Flutter apps don't perform good in debug mode. Are you on latest version of `dart_vlc`?

**Comment by gkovac42** [comment]
https://user-images.githubusercontent.com/23480045/161444416-16969ae1-ed42-469d-9ae4-424074a61c9b.mp4

Here, I'm clicking on the play button at a steady interval, about twice per second. As you can see, the splash animation becomes extremely laggy, and the sound doesn't even play many times.

**Comment by alexmercerind** [comment]
DON'T SPAM IT (?!?!). WHAT ARE YOU TRYING TO PROVE? ALSO RELEASE MODE MAKES MUCH OF A DIFFERENCE. 

EVERY `Player.open` call causes a bunch of `setState` in the example app e.g. video dimension gets changed, playback state gts changed, video frame gets changed, position gets changed.
Also, FFI calls take place on the main-thread, noone has experienced **bAd pErFoRmAnCe** like this except for video playback CPU usage (which is a WIP at #184).
Every time I think I will answer issues with generosity, I get such reports.

**Comment by alexmercerind** [comment]
https://user-images.githubusercontent.com/28951144/161445581-fa78468f-648a-43d1-8c44-97171a870c9a.mp4
(release mode)

Another reason why even a slight delay exists:
It's because all the functions in dart_vlc are completely sync (no Future or await). Everything happens directly because FFI is used.
Platform channels cause native calls to "threshold" or "rate-limit" which people don't notice, but when spamming the button the load on the main thread builds up. Same rate limiting can be implemented in the UI itself.

**Comment by gkovac42** [comment]
Really sorry if you think I tried to spam it to prove something or paint your lib in a bad light, that's really not the case. You see, I have a Windows game build with flutter and I'm trying to implement individual sound playback on various user actions. You can imagine that spamming a button by the player is a very likely scenario in this case. I still haven't figured out how to do something like that with your lib, without breaking the UI. That's all, I hope you understand :)

**Comment by alexmercerind** [comment]
> Really sorry if you think I tried to spam it to prove something or paint your lib in a bad light, that's really not the case. You see, I have a Windows game built with flutter and I'm trying to implement individual sounds playback on various user actions. You can imagine that spamming a button by the player is a very likely scenario in this case. I still haven't figured out how to do something like that with your lib, using a single Player and without breaking the UI. That's all, I hope you understand :)

Then why are you not loading file at once? (i.e. `Player.open`, keep it in memory) & just use `Player.jumpToIndex` whenever your user presses the button.

**Comment by gkovac42** [comment]
Player.jump causes the same framerate issues
