### ISSUE TITLE
Hi when I add this dependicy I couldn't run it

### ISSUE THREAD

**Issue by Abolfazl-MI** [alexmercerind/dart_vlc#245]
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.3 LTS 5.13.0-39-generic,
    locale en_AU.UTF-8)
    • Flutter version 2.10.4 at
      /home/abolfazl/dev/flutter_linux_2.8.1-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/abolfazl/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /home/abolfazl/Android/Sdk
    • Java binary at: /home/abolfazl/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/abolfazl/Desktop/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.67.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.3 LTS 5.13.0-39-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

this is my flutter doctor out put 
when try to run I gaiven this error 
/home/abolfazl/Desktop/sasanProjects/videoplayer/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/api/api.cc:41:48: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
then after while print out this 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Exception: Build process failed
[lease say what shoild I do

**Comment by alexmercerind** [comment]
Show full log using --verbose.

**Comment by Abolfazl-MI** [comment]
> Show full log using --verbose.

witch one ? run or flutter doctor ?

**Comment by alexmercerind** [comment]
flutter run.

You didn't fill the issue template correctly.

**Comment by alexmercerind** [comment]
Linux logs contain no errors by default. That's just a warning in your log.

**Comment by Abolfazl-MI** [comment]
but when I add dependency of that after that it dosent run I want to play movie on dekstop

**Comment by alexmercerind** [comment]
Also install vlc & libvlc-dev from apt beforehand.

**Comment by Abolfazl-MI** [comment]
thanks :)) errors gone Thanks for your help
