### ISSUE TITLE
help~~about flutter texture

### ISSUE THREAD

**Issue by ymmmvp36** [alexmercerind/dart_vlc#25]
hello,i user this to play video.i found it play video in the native window.i want to make it play in the flutter ui. 
i want to use the texture.but i am not good at c++.
do u decide to play the video in the flutter ui?

**Comment by alexmercerind** [comment]
Sorry but this isn't any bug report, discussion or question related to dart_vlc.

**Comment by lycstar** [comment]
Don't you set the width and height for Player.create? you can try once.
