### ISSUE TITLE
Package a minimal version of vlc(if possible) for windows build

### ISSUE THREAD

**Issue by prateekmedia** [alexmercerind/dart_vlc#251]
**Describe the feature you'd like**
I don't know how much features vlc have, but for most of the apps everyone is looking for just a video player with desktop support. So if a minimal version of vlc is packaged with the app then it would be good as not every feature is useful for every app and I don't think this package uses each and every feature of it.

This will help in reducing the final app size.

**Additional context**
Do something like mpv, a custom vlc build

**Other details:**

- [x] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Comment by alexmercerind** [comment]
Sorry. But I cannot decide which plugin(s) users desire in their app, neither their licensing model nor their targeted feature-list. Best is to have it all.

Users can themselves compile VLC and replace the plugins folder or strip it down themselves depending upon their usage.
I maintain the bindings not VLC or users' client code.

See #220.

**Comment by prateekmedia** [comment]
what about only packaging the features that this package uses? I don't think all features are used from vlc in this package.

**Comment by alexmercerind** [comment]
like?

**Comment by alexmercerind** [comment]
https://github.com/mfkl/LibVLC.Windows.Light
