### ISSUE TITLE
failed to create video output!

### ISSUE THREAD

**Issue by Abolfazl-MI** [alexmercerind/dart_vlc#252]
when I add the movie and tap on the play button I got this logs 
[00007fdee002c8c0] main filter error: Failed to create video converter
[00007fdee006efe0] main vout display error: Failed to create video converter
[00007fdee006efe0] main vout display error: Failed to adapt decoder format to display
[00007fdec0002050] main video output error: video output creation failed
[00007fde6c09ad20] main decoder error: failed to create video output
I want to play mp4 videos format and dont really now what and how to implement 
please please please please hep me I am really need it

**Comment by alexmercerind** [comment]
I won't answer any incomplete reports.
Fill details correctly, and give a minimal & compile-able (which I can run) code along with the media that causes the issue. Also ensure that it doesn't happen in VLC itself.

**Comment by Abolfazl-MI** [comment]
so what should I I gave you ? my code and whats? this log is repoedt while video is play in but there is no out put from picture I say that I dont know and I would give you my code and logs then what you need ?

**Comment by Abolfazl-MI** [comment]
I read my all videos from path directory and load as list view and display it then wehn you select one of them you redirect to page with the player section to play video witch you select this opreastion gives the file path to it and sets to read

**Comment by alexmercerind** [comment]
- Create a basic example code which I can use to reproduce your error on my computer.
- Give me the media file or url which causes error.
- Ensure it doesn't happen in VLC desktop app itself.
- I can't just look at VLC logs & tell what's wrong, neither jump inside your computer to fix it.

**Comment by Abolfazl-MI** [comment]
yes but its like your examples and i had remove another widgets I dont neccery need ! just video widget and player controller to play local file with this pathes
file:///home/abolfazl/Videos/finallll.mp4
