### ISSUE TITLE
[Linux][Raspberry-Pi][arm64] "Computer too slow? Too high recursion"

### ISSUE THREAD

**Issue by RadJKW** [alexmercerind/dart_vlc#255]
As the Title shows, I have built an application using Flutter which requires video playback on my raspberry pi running linux arm64. I am running this alongside the default desktop for **_RPi-OS Bullseye_**. The application is functional and can playback some video but not smoothly. 

I also have ubuntu arm64 running on my m1 Mac via parallels and the application works perfectly. The raspberry pi on the other hand is no good. I understand the pi is not that powerful so I'm looking for a possible solution. 

**Details:** 
- Implemented the VLC player almost identical to the repo's example. 
- running on **Raspberry Pi 4b (arm64) 4gb ram**. 
- video file type is **`.wmv`** but can be converted. 
- video is being pulled from _/mnt/networkServer_ which is a mounted **_smb share_** on the local network 

**Issue:** 
- WMV video freezes after first 5 seconds. 
- MP4 video plays but is very choppy and 
- terminal output same for both:  ` **computer too slow?` & `Too high of recursion (3)`** 

**MyTesting:** 
- Opened the VLC application on the raspberry pi and played the exact same video using the networkShare path. 
- Both video types WMV and MP4 played smoothly with little to no issues. 

**Possible Solution:** 
- Is there a way to not allow the video to play until the video is buffered / fully decoded? The video player acts like it is trying to play the video before the cpu / gpu can handle the decoding. When configuring the Player(), are there any options that allow optimizations such as `Player().allowVideoBuffer`?

**Comment by alexmercerind** [comment]
Please use the `GitHub` version of the plugin. 
https://github.com/alexmercerind/dart_vlc#installation
I recently made a fix related to explicit video frame dimensions.

Closing the issue. Progress will be documented at #254. If you have any further questions, feel free to follow up same here.
