### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by chenqiaoyyqx** [alexmercerind/dart_vlc#261]
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (4 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'D:\chenqiao\package_suyangke\suyangke_win\go\build\outputs\windows-debug_unopt\dart_vlc_plugin.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      DartVLC.initialize (package:dart_vlc_ffi/src/internal/initializer.dart:20:39)
#3      DartVLC.initialize (package:dart_vlc/dart_vlc.dart:102:19)
#4      main (package:suyangke_win/main_desktop.dart:29:11)
#5      main (file:///D:/chenqiao/package_suyangke/suyangke_win/.dart_tool/flutter_build/generated_main.dart:91:42)
#6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:128:38)
#7      _rootRun (dart:async/zone.dart:1426:13)
#8      _CustomZone.run (dart:async/zone.dart:1328:19)
#9      _runZoned (dart:async/zone.dart:1861:10)
#10     runZonedGuarded (dart:async/zone.dart:1849:12)
#11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by alexmercerind** [comment]
Fill issue template correctly.
