### ISSUE TITLE
build failed on windows platform:

### ISSUE THREAD

**Issue by chenqiaoyyqx** [alexmercerind/dart_vlc#262]
Describe the bug
can not build app on mac m1 platform
Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'D:\suyangke_win\go\build\outputs\windows-debug_unopt\dart_vlc_plugin.dll'
Minimal reproducible code
import 'dart:io';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get_storage/get_storage.dart';
import 'package:suyangke_win/config/app_theme.dart';
import 'package:flutter/material.dart';
import './pages/index.dart';
import 'package:dart_vlc/dart_vlc.dart';
import 'package:path/path.dart' as path;
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:flutter/foundation.dart';
import 'dart:async';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  DartVLC.initialize();
  await GetStorage.init();
  runApp(myApp());
}

class myApp extends StatefulWidget {
  const myApp({Key? key}) : super(key: key);

  @override
  State<myApp> createState() => _myAppState();
}

class _myAppState extends State<myApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final easyload = EasyLoading.init();
    return ScreenUtilInit(
        designSize: Size(1920, 1080),
        minTextAdapt: true,
        splitScreenMode: true,
        builder: (_) {
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            theme: themeData,
            builder: (context, child) {
              ScreenUtil.setContext(context);
              child = easyload(context, child);
              child = MediaQuery(
                //Setting font does not change with system font size
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: child,
              );
              return child;
            },
            home: IndexPage(),
          );
        });
  }
}

flutter version
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (4 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

Operating system:
Platform: windows10

**Comment by alexmercerind** [comment]
Please re-open the issue with descriptive details about the issue. I can't seem to understand.

You are writing M1 inside issue body & Windows on the issue title. The exception you've referred should also be fixed after latest update i.e. v0.4.0.

Thanks!
