### ISSUE TITLE
Cannot change background color

### ISSUE THREAD

**Issue by fzyzcjy** [alexmercerind/dart_vlc#268]
Hi thanks for the lib! I wonder how to change the background color?

For example, when displaying this video:

![image](https://user-images.githubusercontent.com/5236035/166858477-d2dbd71b-6204-48c1-9619-4956e06e9fa7.png)

I hope the black regions can be white.

p.s. that is a screen recording video, i.e. video content is just a screen. so this screenshot may be a bit misleading.

**Comment by alexmercerind** [comment]
It's not possible to fill the "background", there is no background.

A possible solution is to pass `BoxFit.cover` to `Video` widget & dynamically change the width of `Video` based on aspect ratio (can be obtained via `Stream<VideoDimensions>`). Enclose the `Video` inside another color Container & change color of it instead.

**Comment by fzyzcjy** [comment]
All right... Thank you!

**Comment by alexmercerind** [comment]
> All right... Thank you!

Sorry, edited my reply.

**Comment by fzyzcjy** [comment]
Thank you!
