### ISSUE TITLE
Build failing [MACOS]

### ISSUE THREAD

**Issue by ashutosh2014** [alexmercerind/dart_vlc#269]
Build Failing in Macos 

This is due to **window_manager-0.2.2** packages 
This package have error 
```
error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
            let aspectRatioSize: NSSize = NSMakeSize(aspectRatio, 1.0
```
![Screenshot 2022-05-07 at 7 07 11 PM](https://user-images.githubusercontent.com/48257422/167256852-4b3a30c7-ae3e-4c06-a951-8881385903b2.png)

Issue is resolved by PR https://github.com/leanflutter/window_manager/pull/138

Please update a package version whenever window_manager package version gets updated.

**Comment by alexmercerind** [comment]
I don't have a macOS. I will appreciate a pull-request from you or someone else.
Thanks.
