### ISSUE TITLE
support  m4a?

### ISSUE THREAD

**Issue by luyanggao** [alexmercerind/dart_vlc#277]
**Describe the feature you'd like**

**Additional context**
Add any other context or screenshots about the feature request here (if applicable).

**Operating system:**
- Platform: e.g. Windows, Ubuntu or macOS etc.
- OS version: Windows 11 21H2, Ubuntu 20.04 etc.

**Other details:**

- [ ] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise, do nothing.

**Comment by alexmercerind** [comment]
Don't you think VLC/libVLC is a very capable media player already?
