### ISSUE TITLE
Player.back is not defined in controls.dart

### ISSUE THREAD

**Issue by Varun-Idream** [alexmercerind/dart_vlc#278]
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.9/lib/src/widgets/controls.dart(185,55): error GE5CFE876: The method 'back' isn't defined for the class 'Player'. [E:\windows_app\build\windows\flutter\flutter_assemble.vcxproj]

While running in flutter windows app.
![Capture](https://user-images.githubusercontent.com/94044031/168899176-64a72318-cdc3-478b-b029-f9b5b2cd5378.PNG)

**Operating system:**
- Platform: e.g. Windows,
- OS version: Windows 10

**Other details:**

- [x] I confirm this is not a bug in the VLC app & only `dart_vlc`.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise, do nothing.

**Comment by Varun-Idream** [comment]
Fixed by changing back method to player.previous();

**Comment by alexmercerind** [comment]
Yeah, I changed the API a few days back.
