### ISSUE TITLE
NativeVideo: Video plays in a separate window

### ISSUE THREAD

**Issue by iiijam** [alexmercerind/dart_vlc#280]
**Describe the bug**
I had used the `Video` widget and it worked fine, but the first time started it would lag and take up a lot of resources; so I tried the `NativeVideo` widget, which caused the problem as described in the title
**Media**
I grabbed the live feeds from the web and they all expire after 24 hours, one of them looks like this:
`http://al.flv.huya.com/src/1279513137845-1279513137845-16784091954878087168-2559026399146-10057-A-0-1-imgplus_4000.flv?wsSecret=868a03228a6e8f8d74ec71906fc7d3d3&wsTime=628876ff&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctype=tars_mobile&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&t=103`
**Minimal reproducible code**
```dart
void main() {
  DartVLC.initialize(useFlutterNativeView: true);
  runApp(const MyApp());
}
```
```dart
class StreamPlayer extends StatefulWidget {
  const StreamPlayer({Key? key, required this.title, required this.url})
      : super(key: key);
  final String title;
  final String url;
  @override
  State<StreamPlayer> createState() => _StreamPlayerState();
}

class _StreamPlayerState extends State<StreamPlayer> {
  @override
  Widget build(BuildContext context) {
    final streamPlayer = Player(id: 114514, registerTexture: false);
    final streamInfo = Media.network(widget.url);
    streamPlayer.open(streamInfo, autoStart: true);
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            Navigator.pop(context);
            streamPlayer.stop();
          },
        ),
        title: Text(widget.title),
      ),
      body: Center(
        child: NativeVideo(
          player: streamPlayer,
          showControls: true,
        ),
      ),
    );
  }
}

```

**Flutter logs**
```
[  +15 ms] /C:/Users/USER/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_view-0.0.1+1/lib/src/widgets.dart:87:20: Warning: Operand
of
           null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[   +2 ms]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
            ('/C:/Users/USER/AppData/Local/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.addPostFrameCallback(
[        ]                    ^
```
```
paste output of **[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.22000.675], locale zh-CN)
    • Flutter version 3.0.0 at C:\Users\USER\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (10 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [版本 10.0.22000.675]

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!** here (replace this line, and make sure to include --verbose flag).
```

**Operating system:**
- Platform: Windows
- OS version: Windows 11 21H2,22000.675

**Other details:**

- [x] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**
<img width="1280" alt="屏幕截图 2022-05-20 132433" src="https://user-images.githubusercontent.com/16839488/169458346-7adca722-dd94-4598-afc3-db0b1aa6d08a.png">

**Comment by alexmercerind** [comment]
Hi! thanks for the descriptive report.

I'm currently unable to reproduce this in the example application.

Did you make [these](https://github.com/alexmercerind/flutter_native_view#setup) changes in your `windows/main.cpp` ?

![](https://user-images.githubusercontent.com/28951144/169481055-7e54d2d8-fc66-4ada-9d09-8426280d919c.png)

**Comment by iiijam** [comment]
Solved.

**Comment by alexmercerind** [comment]
> Solved.

I wanted to additionally cite that "first-time" lag is something I also notice but don't know the exact reason. It can be seen in other Flutter plugins too. I think some native-type marshalling or libvlc itself causes this. Honestly, I have no clue about this one.

`NativeVideo` actually embeds the VLC window directly, which is a lot lot lot better for CPU & battery of the computer. `Video` uses `libvlc_set_video_callbacks` which is not good in term of performance.
