### ISSUE TITLE
Sound of specific network media cannot be played

### ISSUE THREAD

**Issue by iiijam** [alexmercerind/dart_vlc#281]
**Describe the bug**
As the title describes, the sound of a particular network media cannot be played, but they can be played normally in VLC
**Media**
`http://al.flv.huya.com/src/78941969-2558924260-10990496009641000960-3143878788-10057-A-0-1-imgplus_4000.flv?wsSecret=47917551f11591eaaa72d51958a5b066&wsTime=6289c937&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctype=tars_mobile&txyp=o%3An4%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&t=103`
This address will expire in 24 hours, if it does, please try the following steps:

1. run [this python scrpit](https://gist.github.com/iiijam/84e4f8b60872516bd8efe1621b914521)
2. enter 0, 1 or 2
3. copy the generated address

**Minimal reproducible step**

1. clone dart_vlc
2. run example
3. enter the media address in example
4. ernter the media address in vlc

**Flutter logs**
```
[  +98 ms] Syncing files to device Windows...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +1 ms] <- recompile package:dart_vlc_example/main.dart 0803095a-1b4f-4450-855b-472f3be41971
[        ] <- 0803095a-1b4f-4450-855b-472f3be41971
[   +1 ms] Bundle processing done.
[  +18 ms] /C:/Users/USER/AppData/Local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_view-0.0.1+1/lib/src/widgets.dart:87:20: Warning: Operand
of
           null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[   +2 ms]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
            ('/C:/Users/USER/AppData/Local/flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.addPostFrameCallback(
[        ]                    ^
[ +107 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Windows... (completed in 135ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x1c8b4b1aa10.
```
```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.22000.675], locale zh-CN)
    • Flutter version 3.0.0 at C:\Users\USER\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (11 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [版本 10.0.22000.675]

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Operating system:**
- Platform: Windows
- OS version: Windows 11 21H2

**Other details:**
- [x] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16839488/169638274-9ff318bb-64af-4798-9799-56b454c9ec4a.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16839488/169638314-b629246b-24d9-4049-b396-b0e6ebd4ea31.png">

**Comment by alexmercerind** [comment]
I don't change behavior of audio decoder or handle manual callbacks for it... You could try updating the libvlc version used in the plugin.

See: [vlc-3.0.9.2.7z](https://github.com/alexmercerind/dart_vlc/blob/master/bin/vlc-3.0.9.2.7z)](https://github.com/alexmercerind/dart_vlc/tree/master/bin). 
Download new versions from [here](http://download.videolan.org/vlc/).

You can actually strip the size of your application by deleting the DLL files that aren't required by the video formats you're playing.

**Comment by alexmercerind** [comment]
Closing as no response.

**Comment by iiijam** [comment]
Sorry for the late reply, I updated libvlc.dll and libvlccore.dll and all the dlls in plugins to vlc 3.0.16 (with the vlc I already installed), the problem seems to be solved, I found that the dll used by dart_vlc is older. Can you update to the latest version?

I'm not very clear on which dlls can be removed, my application needs to play flv streams, is there a guide on how to remove them?

**Comment by alexmercerind** [comment]
> Sorry for the late reply, I updated libvlc.dll and libvlccore.dll and all the dlls in plugins to vlc 3.0.16 (with the vlc I already installed), the problem seems to be solved, I found that the dll used by dart_vlc is older. Can you update to the latest version?

Sure, from next version.

> I'm not very clear on which dlls can be removed, my application needs to play flv streams, is there a guide on how to remove them?

Technically, it is recommended to compile your own copy of libVLC/VLC for distribution that fits your purpose & licensing-model of the application you're making. Since, most people can't compile VLC that easy, they can delete the DLLs present which aren't used in their app (which works because they're dynamically linked). It's just trial & error (+ bit of research that you may do online to figure out which plugin is responsible for what).

<hr></hr>

Apart from above, it is recommended that you update to the latest version of plugin because I have fixed an issue related to `NativeVideo` there.
