### ISSUE TITLE
Bug: Unable to create a windows build from version 0.1.7 to 0.2.0

### ISSUE THREAD

**Issue by MalteBoehm** [alexmercerind/dart_vlc#282]
Hey there, 

somehow, i'm not able to build anything on Windows 11 with dart_vlc. I always get this sort of report. 

I use the latest stable version of dart and flutter.

Thank you very much

/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.1.9/lib/src/widgets/controls.dart(185,55): error G76A9B1F6: The method 'back' isn't defined for the class 'Player'. [C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Der benutzerdefinierte Build f�r "C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\CMakeFiles\e98853f581c37bfc0e218fc29ee9c627\flutter_windows.dll.rule;C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\CMakeFiles\c339ceab05c763d608fa9068abed8dc9\flutter_assemble.rule" wurde mit dem Code 1 beendet. [C:\Projects\flutter_manager\packages\convenient_test_manager\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

**Comment by alexmercerind** [comment]
There have been few API changes & how things are bundled. A `flutter clean` should've been enough.
