### ISSUE TITLE
IOS Crash 

### ISSUE THREAD

**Issue by C-Kristal** [alexmercerind/dart_vlc#284]
I  Tested in A NewProject , if i use dart_vlc in project, and without write any "vlc_about_code"
,it will throw that Error;

Dev Device MacOS 12.2.1
phone ios 14.2

Xcode build done.                                           26.8s
(lldb) dyld: symbol '__ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE' not found, expected in '/usr/lib/libc++.1.dylib', needed by '/private/var/containers/Bundle/Application/2936BA43-4E9C-498D-B383-28F0F048BEA0/Runner.app/Frameworks/dart_vlc.framework/dart_vlc'
* thread #1, stop reason = EXC_BAD_ACCESS (code=1, address=0x105038480)
    frame #0: 0x0000000104bfd4e4 dyld`strlen + 4
dyld`strlen:
->  0x104bfd4e4 <+4>:  ldr    q0, [x1]
    0x104bfd4e8 <+8>:  adr    x3, #-0xc8                ; ___lldb_unnamed_symbol3$$dyld
    0x104bfd4ec <+12>: ldr    q2, [x3], #0x10
    0x104bfd4f0 <+16>: and    x2, x0, #0xf
Target 0: (Runner) stopped.

**Comment by alexmercerind** [comment]
No support for iOS from me #242.

**Comment by GroovinChip** [comment]
Fixed by #276
