### ISSUE TITLE
Error compiling Linux desktop application

### ISSUE THREAD

**Issue by rafaelbm9126** [alexmercerind/dart_vlc#287]
# Error compiling Linux desktop application

### Console output:

$ flutter run         
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-44-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on Linux in debug mode...
/home/xxx/Desktop/FluterProjects/desktop/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/api/api.cc:41:48: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Building Linux application...                                           
Exception: Build process failed

### Error message:

warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]

### Error File:

dart_vlc/dartvlc/api/api.cc:41:48

### Environment data:

Ubuntu 20.04 x64

Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-44-generic, locale en_US.UTF-8)

Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

**Comment by alexmercerind** [comment]
That's not error, that's warning. Show full logs using `--verbose` as asked in issue template.
Likely you didn't install libvlc-dev & vlc from apt.
