### ISSUE TITLE
Timer images in Playlist

### ISSUE THREAD

**Issue by fulcri** [alexmercerind/dart_vlc#288]
**Describe the feature you'd like**
When you put images in a playlist you can see them without problems. 
The images are shown for like 10 seconds.
It would be good amazing to be able to control the time each image is shown 
(the timeout parameter is ignored)

Another cool feature could be the possibility to add a transition beetween images and video in a playlist

**Comment by alexmercerind** [comment]
Why are you using a video-playback solution for image viewing??? It's expensive for your GPU & CPU, you know it right?

Still, you can change that duration using a CLI parameter called `--image-duration`. Learn more at [official documentation](https://wiki.videolan.org/VLC_command-line_help/).

**Comment by alexmercerind** [comment]
https://pub.dev/packages/carousel_slider
