### ISSUE TITLE
macOS build error Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ZoubairDaddow** [alexmercerind/dart_vlc#291]
When I try to build macOS this error appear : 

Undefined symbols for architecture arm64:
  "Player::SetVideoFrameCallback(std::__1::function<void (unsigned char*, int, int)>)", referenced from:
      -[VideoOutlet initWithPlayer:textureRegistry:] in VideoOutlet.o
      -[VideoOutlet dispose] in VideoOutlet.o
  "_g_players", referenced from:
      +[VideoOutlet outletForPlayer:withTextureRegistry:] in VideoOutlet.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![image](https://user-images.githubusercontent.com/32312290/172046508-0ea0b91f-4214-44f0-b877-3f78c02ecd92.png)

**dart_vlc: ^0.2.1**

**Flutter Doctor :** 
mac@macs-Mac-mini pub.dartlang.org % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
This is taking an unexpectedly long time...[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] VS Code (version 1.63.2)
Scanning for devices is taking a long time...[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
mac@macs-Mac-mini pub.dartlang.org %

**Comment by 2803404074** [comment]
遇到同样的错误

**Comment by alexmercerind** [comment]
See https://github.com/alexmercerind/dart_vlc/pull/285.
I can't help macOS.

**Comment by ollydixon** [comment]
@ZoubairDaddow if you're still stuck, I've made a MacOS video player. https://pub.dev/packages/video_player_macos

**Comment by ZoubairDaddow** [comment]
> @ZoubairDaddow if you're still stuck, I've made a MacOS video player. https://pub.dev/packages/video_player_macos

Thanks @ollydixon
I tried better_player and video_player 
 for **UDP**  protocol and it isn't working

**Comment by ollydixon** [comment]
UDP would be for live stream players. Static video playing using hosted files only use TCP.

**Comment by GroovinChip** [comment]
I've been working really hard trying to fix this problem and I've gotten nowhere. @alexmercerind I recommend that `dart_vlc` drops macOS until this can be resolved - you don't officially support it anyway, since you don't have a mac. Including broken platform support isn't a good look, and it breaks Flutter apps that support mobile and desktop - mac versions of such apps do not build at all.

**Comment by fzyzcjy** [comment]
Well it works perfectly fine for macos version of https://github.com/fzyzcjy/flutter_convenient_test - it compiles and runs well! Removing macos support will make that app not work at all after upgrading.

**Comment by GroovinChip** [comment]
> Well it works perfectly fine for macos version of https://github.com/fzyzcjy/flutter_convenient_test - it compiles and runs well! Removing macos support will make that app not work at all after upgrading.

Feel free to fork `dart_vlc` and add macos support back to it, then. And if you can make it work reliably, feel free to open a PR back to this repo.
