### ISSUE TITLE
Change color of speakers menu

### ISSUE THREAD

**Issue by chamodeveloper** [alexmercerind/dart_vlc#293]
**Describe the bug**
I am trying to show a video in a dialog when you tap on an item of a listview.
Explain the bug.
When the video is shown all controls look great but if we go to the last icon in the video controls which is the speaker menu, the background is white and the letters too, which make it hard to distinguis the selection of items.

**Media**

Upload / give URL of the audio/video files that cause the issue (if applicable).

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/99205618/172930937-750394a6-d275-4cdf-b504-110a867a19d9.png">

Is there a property to tweak that? Or at least to hide it?

**Comment by alexmercerind** [comment]
> Is there a property to tweak that? Or at least to hide it?
Hide the controls & write your own.

Those default controls were present for the example application & for lazy people.

**Comment by alexmercerind** [comment]
Ideally, you should create your own controls (use `Stack` widget & other streams in `Player`).
The default minimal look is just for quick usability purpose.
