### ISSUE TITLE
Incomatibility w/ flutter_acrylic

### ISSUE THREAD

**Issue by zSoulweaver** [alexmercerind/dart_vlc#297]
**Describe the bug**
Using video when using most effects from `flutter_acrylic` will cause the video to be blank/black and only audio to play. Even using the disabled effect will still cause the video to be blank. This is whilst using the `useFlutterNativeView` set to true, if I don't use the native player I get a black video regardless.

**Media**

n/a

**Minimal reproducible code**
```dart
flutter_acrylic.Window.setEffect(effect: flutter_acrylic.WindowEffect.solid);
```

**Flutter logs**
I don't quite think this is needed, but let me know and I'll paste em in, they're a bit long.

**Operating system:**
- Platform: Windows.
- OS version: Windows 11 21H2 (22000.708)

**Other details:**

- [ ] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise, do nothing.

**Comment by alexmercerind** [comment]
There's no way around it. Moving issue to flutter_native_view repository.
