### ISSUE TITLE
How can I get AspectRatio of the current media?

### ISSUE THREAD

**Issue by 0Franky** [alexmercerind/dart_vlc#298]
Hi alexmercerind,
thank you for your work and this awesom plugin.

I want to ask you how get the aspectRatio during the playing of a media.
I searched but I have not found anything useful.

Thank you in advanced.

**Comment by 0Franky** [comment]
Thank you for your reply @alexmercerind!
This is a good solution.
But I found another problem. Starting this video: 
https://assets.mixkit.co/videos/preview/mixkit-portrait-of-a-fashion-woman-with-silver-makeup-39875-large.mp4
the stream catch two different dimensions.
The first one is the correct, the second one have 5 more pxs on the height.

PS, I'm using
```
double aspectRatio = _vlcController.videoDimensions.width / _vlcController.videoDimensions.height;
```
and this take the last dimension (correctly).

Do you have any solution for that?


Thank you!

**Comment by alexmercerind** [comment]
I can't say much regarding this. Callbacks are forwarded from libvlc into Dart's stream interface. You could try updating the VLC version inside plugin.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/dart_vlc/blob/master/bin/vlc-3.0.9.2.7z or directly replace dll files in your exe folder.

**Comment by 0Franky** [comment]
Ok, thank you so much!
I will try today and write the updates here so as to help the next ones who have the same problem as well. 
If I resolve I can open a PR to update the VLC version. 

Thank you again

**Comment by 0Franky** [comment]
> https://github.com/alexmercerind/dart_vlc/blob/master/bin/vlc-3.0.9.2.7z o sostituisci direttamente i file dll nella cartella exe.

I want to try to update this version of vlc, but there are several sdks on vlc site. Can you indicate me the correct one so as to update it and open a PR?

**Comment by LULU233333** [comment]
> Thank you for your reply @alexmercerind! This is a good solution. But I found another problem. Starting this video: https://assets.mixkit.co/videos/preview/mixkit-portrait-of-a-fashion-woman-with-silver-makeup-39875-large.mp4 the stream catch two different dimensions. The first one is the correct, the second one have 5 more pxs on the height.
> 
> PS, I'm using
> 
> ```
> double aspectRatio = _vlcController.videoDimensions.width / _vlcController.videoDimensions.height;
> ```
> 
> and this take the last dimension (correctly).
> 
> Do you have any solution for that?
> 
> Thank you!

Edit the file: [dart_vlc](https://github.com/alexmercerind/dart_vlc)/[core](https://github.com/alexmercerind/dart_vlc/tree/master/core)/[player](https://github.com/alexmercerind/dart_vlc/tree/master/core/player)/[player.cc](https://github.com/alexmercerind/dart_vlc/blob/master/core/player/player.cc)

![20220823205207](https://user-images.githubusercontent.com/69127442/186162669-ff987e07-7c55-4e2b-9ef8-fdd8f924bac4.png)
