### ISSUE TITLE
[Question] What about providing a constructor or making `create` synchronous

### ISSUE THREAD

**Issue by narumishi** [alexmercerind/dart_vlc#3]
Hey @alexmercerind , I want to discuss such a question just saied in title.

Currently, `Player.create` is `async`, I would like to create a Player instance inside some constructor, then I need to check the instance is created or not before calling any method.

What if remove `await` for  MethodChannel `create`, and check it before other methods called inside package, for example, use a `Completer` to ensure instantiation completed. Although it makes code messy somehow, but it would be more friendly to users who use the library.

And then, players are saved in `players`, how about use a factory constructor to reuse the player instance with the same id. Currently, create a new instance without check.

**Comment by alexmercerind** [comment]
Hi there @narumishi !

Umm I was using a synchronous constructor in the previous project, as you might recall. But that used to cause bit of problems, as people used to call any method directly after creating of object in the same method & then used to report me bugs, so I made it completely safe this time 😟.

I feel this project would be much stable for you compared to older one.

I'll look forward to get what you said.

Thanks.

**Comment by narumishi** [comment]
Here is example code under my assumption
```dart
import 'dart:async';

import 'package:flutter/services.dart';

late MethodChannel channel;

class Player {
  int id;
  static Map<int, Player> _players = {};

  Completer<void>? _completer;

  factory Player({required int id}) {
    if (_players.containsKey(id)) return _players[id]!;
    final Player _player = Player._(id);
    _players[id] = _player;
    return _player;
  }

  Player._(this.id) {
    ensurePlayer();
  }

  Future<void> ensurePlayer() async {
    if (_completer != null) return _completer!.future;
    _completer = Completer();
    await channel.invokeMethod(
      'create',
      {
        'id': id,
      },
    );
    _completer!.complete();
  }

  Future<void> play() async {
    await ensurePlayer();
    await channel.invokeMethod(
      'play',
      {
        'id': this.id,
      },
    );
  }
}
```

**Comment by alexmercerind** [comment]
Thanks.
Seeing this code reminds me that I haven't even migrated to null safety yet.

**Comment by narumishi** [comment]
Just compiled the windows version... I have never thought `libvlc` will generate 120MB files in `plugins` folder which is still 60MB large after zipped.

Is there any options to decrease `plugins` folder size while most of them of useless if I just want to play mp3/wav audios?

**Comment by alexmercerind** [comment]
> Just compiled the windows version... I have never thought libvlc will generate 120MB files in plugins folder which is still 60MB large after zipped.
This project does not compile libVLC itself, but fetches shared libraries & headers etc. directly from VideoLAN severs, if I could compile libVLC myself, then it could be possible to select the plugin that one wants. 

> Is there any options to decrease plugins folder size while most of them of useless if I just want to play mp3/wav audios

All I can say right now, is "trial and error", as far as I'm aware there are many many plugins for video decompression, even Qt window etc. that you might won't need. So, you can just try and delete the folders/DLLs that you find unnecessary. 

This is where miniaudio version was lightweight (a lot) than this.

**Comment by alexmercerind** [comment]
Okay finally.
