### ISSUE TITLE
Does the "extras" parameter work ?

### ISSUE THREAD

**Issue by Spsden** [alexmercerind/dart_vlc#311]
**Describe the bug**
 I am not able to get the "extras" parameter to work.
```dart
 Map<String,dynamic> _map = {'Usrname':'tom','Password':'pass@123'};
 Media.network( controller.text,
extras: _map,),
                                                  );
```
There is no option to access "extras",

```dart
player.current.media. ???
```

How do I access it ?

Excellent work btw, Thanks for it..

**Comment by alexmercerind** [comment]
Shameless to say, it actually broke few release ago & hasn't been fixed since no-one asked for it surprisingly.

**Comment by Spsden** [comment]
> Shameless to say, it actually broke few release ago & hasn't been fixed since no-one asked for it surprisingly.

I guess, I'll have to wait for a future release then, till then let's see if I can workaround or something..

**Comment by alexmercerind** [comment]
As a dirty alternative, you could create a global `Map` object to keep data for each unique media URI.

**Comment by Spsden** [comment]
I did something like that in an earlier build of my project.
```dart
List<Map<String,dynamic>>
```
and accesing it through 
```dart
player.current.media.index
```
 Just recently discovered the extras option, so tried to use it.

**Comment by alexmercerind** [comment]
Removed the parameter altogether for now.
I will open-source a new package with reduced size & hardware-accelerated video playback etc.
