### ISSUE TITLE
Position/PositionState Update frequency

### ISSUE THREAD

**Issue by felipeuematsu** [alexmercerind/dart_vlc#321]
Hello, I am currently making an app that will rely on getting the updated position in milliseconds of the media I'm currently playing.

Right now, I have an issue where the Duration returned by the position API is the same for approximately 6 of the instances produced by the stream.

I'd like to know if there's a way for it to be fixed or to be able to set the frequency of the updates of the position stream.

The behavior is the same whether I use the positionStream or try querying the position multiple times.

**Comment by HAFIZkhan-source** [comment]
We are also facing the same issue. Any Update on this?

**Comment by alexmercerind** [comment]
This is the update.
