### ISSUE TITLE
when 'showFullscreenButton' is true, the fullscreen button only shown in normal mode, but disappeared in fullscreen mode

### ISSUE THREAD

**Issue by jakky1** [alexmercerind/dart_vlc#322]
The fullscreen button should be displayed in fullscreen mode too.
Or user can press button to enter fullscreen mode, but no way to exit...

          Video(
            player: player,
            showFullscreenButton: true,
          )

It seems we have to pass the 'showFullscreenButton' into 'Control' class in enterFullscreen() of video.dart, line#209

**Comment by alexmercerind** [comment]
Removed in-package fullscreen support in latest v0.4.0 update.

It is a better idea that client apps implement their own full-screen implementation using `package:window_manager` etc. & handle positioning of `Video` widget etc. Previous implementation could conflict or raise problems as it did for you (especially when using other plugins which alter the native behavior of the window).
