### ISSUE TITLE
How to Loop/Repeat ?

### ISSUE THREAD

**Issue by IfProgrammingIsMagicImaWizard** [alexmercerind/dart_vlc#332]
I tried with `commandlineArguments: ['--repeat --loop'],` but it doesn't work.

**Comment by rrrovalle** [comment]
You can use PlaybackState and wait for isCompleted event, then just play it again. like:

```
    player.playbackStream.listen((PlaybackState state) {
      if (state.isCompleted) {
        player.play();
      }
    });
    player.open(localMedia, autoStart: true);
```

**Comment by Bnk970** [comment]
`player.setPlaylistMode(PlaylistMode.loop);`

**Comment by alexmercerind** [comment]
The question has been answered.

CONSIDER READING THE DOCUMENTATION CAREFULLY.
