### ISSUE TITLE
Update ffi to 2.x

### ISSUE THREAD

**Issue by imtoori** [alexmercerind/dart_vlc#334]
**Describe the feature you'd like**

At the moment the package uses `ffi: 1.x` and this can cause conflicts with packages using more recent versions of ffi

**Additional context**
For example: https://github.com/GetStream/stream-chat-flutter/issues/1344

**Other details:**

- [X] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [x] I have donated / sponsored `dart_vlc`.

**Comment by MichaelMarner** [comment]
Looking at the changelog, the only difference between ffi 1.0 and 2.0 is an update to the minimum dart version

> Switch Windows memory allocation to use CoTaskMemAlloc and CoTaskMemFree, which will enable support for NativeFinalizer. This release requires Dart 2.17.0 or greater.

https://pub.dev/packages/ffi/changelog

**Comment by alexmercerind** [comment]
Apologies for the inactivity. This is a really minor issue & should've been fixed early on.

I have released a new version [dart_vlc: ^0.4.0](https://github.com/alexmercerind/dart_vlc/releases/tag/v0.4.0) with required changes & few other fixes.

<hr>

Thanks for the patience. I've been inactive for some days. Actively updating & maintaining open-source packages (package:dart_vlc & others on my profile) has been very tedious, aside from actual development process & writing code for the project. And... C++ & writing native code is even more time consuming.
I just decided to stop & un-watch my repositories. All this brought no significant benefit (or no benefit at all) to my life, just additional un-appreciated work & more responsibilities. I used to end-up waste a lot of my time daily helping out people & my e-mail also used to get cramped daily. I added few other collaborators on pub.dev & GitHub to keep the maintenance on track, however it's again just me doing it. On the other hand, I've been somewhat dissatisfied with current state of this package & aiming for a more performant video playback solution for Flutter (specifically Windows & Linux are concerned for now). More on that here: #345. Altogether, I completely lost interest. 

Yesterday, some kind folks at [Stream](https://getstream.io/) decided to reach me out on my e-mail (I can see their referenced issues above) & sponsor package:dart_vlc & future improvements that I make for rendering video in Flutter (initially limiting scope to Windows & Linux).
Hoping to make some good improvements to the ecosystem.
