### ISSUE TITLE
Unable to load audio files from /storage/emulated/0 and its sub-directories

### ISSUE THREAD

**Issue by Farial-mahmod** [alexmercerind/dart_vlc#347]
This plugin no more is able to load audio files from /storage/emulated/0 and its sub-directories . The error status is: LateError (LateInitializationError: Field 'dynamicLibrary')

**Plugin version: dart_vlc: ^0.1.9 **

**Operating system:**
Tested on:
Android OS emulator and the project was running on Parrot Security OS .

Kindly, check .

**Comment by husainazkas** [comment]
Am I misreading or misunderstanding? This package is only support for Flutter Desktop app such as Windows and Linux. Why did you use this package in your android project?
