### ISSUE TITLE
[ Linux ] clang: error: linker command failed with exit code 1 (use -v to see invocation) Exception: Build process failed

### ISSUE THREAD

**Issue by secanonm** [alexmercerind/dart_vlc#354]
**Describe the bug**

[Explain the bug.](clang: error: linker command failed with exit code 1 (use -v to see invocation) Exception: Build process failed)

**Minimal reproducible code**
```dart
replace this line with the code that causes bug (code should be compile-able & single-file)
```

**Flutter logs**
[        ] [  +13 ms] invalidated build due to missing files:
/home/secanonm/Desktop/Project/Scupper/scupper-pc/DOES_NOT_EXIST_RERUN_FOR_WILDCARD722281279
[  +13 ms] [ +988 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing:
/home/secanonm/Desktop/Project/Scupper/scupper-pc/DOES_NOT_EXIST_RERUN_FOR_WILDCARD722281279}
[        ] [+3055 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see
#56466.
[        ] [+1606 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +973 ms] Persisting file store
[        ] [  +37 ms] Done persisting file store
[        ] [  +48 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 9,595ms.
[        ] [ +258 ms] ensureAnalyticsSent: 252ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[+1670 ms] [2/5] Building CXX object CMakeFiles/scupper.dir/flutter/generated_plugin_registrant.cc.o
[   +7 ms] [3/5] Building CXX object CMakeFiles/scupper.dir/my_application.cc.o
[ +331 ms] [4/5] Linking CXX executable intermediates_do_not_run/scupper
[   +5 ms] FAILED: intermediates_do_not_run/scupper 
[  +19 ms] : && /snap/flutter/current/usr/bin/clang++  -g  -B/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9
-B/snap/flutter/current/usr/lib/x86_64-linux-gnu -B/snap/flutter/current/lib/x86_64-linux-gnu -B/snap/flutter/current/usr/lib/
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu
-L/snap/flutter/current/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ -lblkid -lgcrypt -llzma -llz4 -lgpg-error -luuid -lpthread -ldl
-lepoxy CMakeFiles/scupper.dir/main.cc.o CMakeFiles/scupper.dir/my_application.cc.o
CMakeFiles/scupper.dir/flutter/generated_plugin_registrant.cc.o  -o intermediates_do_not_run/scupper
-Wl,-rpath,/home/secanonm/Desktop/Project/Scupper/scupper-pc/build/linux/x64/debug/plugins/dart_vlc:/home/secanonm/Desktop/Project/Scupper/scup
per-pc/build/linux/x64/debug/plugins/flutter_meedu_videoplayer:/home/secanonm/Desktop/Project/Scupper/scupper-pc/build/linux/x64/debug/plugins/
pasteboard:/home/secanonm/Desktop/Project/Scupper/scupper-pc/build/linux/x64/debug/plugins/screen_retriever:/home/secanonm/Desktop/Project/Scup
per/scupper-pc/build/linux/x64/debug/plugins/url_launcher_linux:/home/secanonm/Desktop/Project/Scupper/scupper-pc/build/linux/x64/debug/plugins
/window_manager:/home/secanonm/Desktop/Project/Scupper/scupper-pc/linux/flutter/ephemeral:  plugins/dart_vlc/libdart_vlc_plugin.so
plugins/flutter_meedu_videoplayer/libflutter_meedu_videoplayer_plugin.so  plugins/pasteboard/libpasteboard_plugin.so
plugins/screen_retriever/libscreen_retriever_plugin.so  plugins/url_launcher_linux/liburl_launcher_linux_plugin.so
plugins/window_manager/libwindow_manager_plugin.so
/home/secanonm/Desktop/Project/Scupper/scupper-pc/linux/flutter/ephemeral/libflutter_linux_gtk.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libharfbuzz.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +3 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlc.so.5: undefined reference to `__pthread_register_cancel@GLIBC_2.34'
[   +2 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_setspecific@GLIBC_2.34'
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `dlopen@GLIBC_2.34'
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_rwlock_init@GLIBC_2.34'
[   +3 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `fstat64@GLIBC_2.33'
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_rwlock_wrlock@GLIBC_2.34'
[  +17 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_sigmask@GLIBC_2.32'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_testcancel@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to
`pthread_condattr_setclock@GLIBC_2.34'
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `dlerror@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `stat64@GLIBC_2.33'
[   +4 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_getspecific@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_create@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `sem_init@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to
`pthread_mutexattr_destroy@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `sem_destroy@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to
`pthread_attr_setstacksize@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_cancel@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to
`pthread_mutexattr_settype@GLIBC_2.34'
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_join@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `dlclose@GLIBC_2.34'
[   +7 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to
`__pthread_unregister_cancel@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_rwlock_rdlock@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_key_delete@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `sem_post@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_once@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `sem_wait@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_rwlock_destroy@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_key_create@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `pthread_rwlock_unlock@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `dlsym@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `lstat64@GLIBC_2.33'
[   +7 ms] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +8 ms] ninja: build stopped: subcommand failed.

**Operating system:**
- Platform: Linux.
- OS version: kali linux 2023.4.

**Comment by alexmercerind** [comment]
Don't use Snap installation of Flutter. How will it be able to use libVLC from your package manager? Think for yourself.
