### ISSUE TITLE
Multiple Video Players in an app

### ISSUE THREAD

**Issue by angelocordero** [alexmercerind/dart_vlc#357]
**Describe the feature you'd like**
Is it possible to have multiple video players in a single app? Currently I receive this error when I have 2 Video widgets present and playing at the same time

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      receiver.<anonymous closure>
package:dart_vlc_ffi/…/internal/ffi.dart:202
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#5      _StreamController._add (dart:async/stream_controller.dart:648:7)
#6      _StreamController.add (dart:async/stream_controller.dart:596:5)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Additional context**

**Operating system:**
- Linux and Windows 10 and 11

**Other details:**

- [ ] I confirm this is not a bug in the VLC app & only `dart_vlc`.
- [ ] I have donated / sponsored `dart_vlc`.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise, do nothing.

**Comment by alexmercerind** [comment]
Have you considered giving [package:media_kit](https://github.com/alexmercerind/media_kit) a try?

It's far (far-far) more stable & performant.
