### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by trunghieuvn** [alexmercerind/dart_vlc#42]
I upgrade to new version and has issue: when resize windows

![image](https://user-images.githubusercontent.com/19247680/116768660-8c29d200-aa62-11eb-99db-f32594ae4da7.png)

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building Control(dirty, state: _ControlState#40024):
Null check operator used on a null value

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
When the exception was thrown, this was the stack
#0      _ControlState.build
package:dart_vlc/…/widgets/controls.dart:110
#1      StatefulElement.build
package:flutter/…/widgets/framework.dart:4612
#2      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4495
#3      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4667
#4      Element.rebuild
package:flutter/…/widgets/fram
```

**Comment by trunghieuvn** [comment]
Hi @alexmercerind  this issue is still happening in v0.0.7

![image](https://user-images.githubusercontent.com/19247680/117572346-b0d61780-b0fc-11eb-8e9b-a12b393485ba.png)

some frame will have issue in line `396`

![image](https://user-images.githubusercontent.com/19247680/117572372-cb0ff580-b0fc-11eb-8073-5d6eebb1d956.png)

**Comment by alexmercerind** [comment]
@trunghieuvn is there something that you can do to fix it?
I haven't encountered this, I'll be happy to receive a pull request.
