### ISSUE TITLE
Version .0.0.6 fails on windows

### ISSUE THREAD

**Issue by syleishere** [alexmercerind/dart_vlc#48]
Fails on 0.0.6, .0.0.5 works fine:

Building Windows application...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: The command "setlocal [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: cd C:\flutter\musicplayer\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\windows\bin [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: C: [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E tar xzf "C:/flutter/musicplayer/windows/flutter/ephemeral/.plugin_symlinks/dart_vlc/windows/bin/vlc-3.0.9.2.7z" [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E tar xzf "C:/flutter/musicplayer/windows/flutter/ephemeral/.plugin_symlinks/dart_vlc/windows/bin/libvlcpp.zip" [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_directory C:/flutter/musicplayer/windows/flutter/ephemeral/.plugin_symlinks/dart_vlc/windows/bin/vlc-3.0.9.2/sdk/include/vlc C:/flutter/musicplayer/windows/flutter/ephemeral/.plugin_symlinks/dart_vlc/windows/include/vlc [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_directory C:/flutter/musicplayer/windows/flutter/ephemeral/.plugin_symlinks/dart_vlc/windows/bin/libvlcpp-master/vlcpp C:/flutter/musicplayer/windows/flutter/ephemeral/.plugin_symlinks/dart_vlc/windows/include/vlcpp [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: :cmEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: :cmErrorLevel [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: exit /b %1 [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: :cmDone [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: :VCEnd" exited with code 1. [C:\flutter\musicplayer\build\windows\plugins\dart_vlc\LIBVLC_EXTRACT.vcxproj]

**Comment by plplplpla** [comment]
look at the pinned issues

**Comment by DomingoMG** [comment]
Check if it is due to the same problem: # 32

**Comment by syleishere** [comment]
Nope, I have tried flutter clean etc no difference. Its error number MSB3073 from visual studio. I looked around net thinking it was an un-writeable directory error etc but directories in question are writeable, not sure what issue is, but that is what error code seems to relate to.

**Comment by syleishere** [comment]
C:\flutter\musicplayer>dart --version
Dart SDK version: 2.14.0-48.0.dev (dev) (Tue Apr 27 02:32:06 2021 -0700) on "windows_x64"

**Comment by syleishere** [comment]
Honestly I think it was working earlier today, but I think I upgraded to newest dart version today and think it broke then

**Comment by syleishere** [comment]
C:\src\flutter\bin\flutter.bat --no-color upgrade
Flutter is already up to date on channel master
Flutter 2.3.0-1.0.pre.227 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7f1d1414cc (11 hours ago) • 2021-05-04 06:17:19 -0700
Engine • revision 378e4dbc41
Tools • Dart 2.14.0 (build 2.14.0-48.0.dev)

**Comment by syleishere** [comment]
I believe the framework revision above is breaking it, see if you can update to that revision and try it.

**Comment by syleishere** [comment]
Maybe not further investigating and looking at issue: https://github.com/alexmercerind/dart_vlc/issues/13
about a file that cannot be downloaded:
`dandesktop:/mnt/c/Users/dan/AppData/Local/Pub/Cache/hosted/pub.dartlang.org # rm -rf dart_vlc-0.0.6`

then running flutter pub get again I try to run it, it just hangs infinitely like it is trying to download a file it cannot, something to do with that china github?

So it just hangs and if I hit stop because tired of waiting at this point, that will produce error in the post.

**Comment by alexmercerind** [comment]
Invalid.
