### ISSUE TITLE
Unable to play MediaType.File on Windows

### ISSUE THREAD

**Issue by plplplpla** [alexmercerind/dart_vlc#49]
Example showed that MediaType.File worked on Linux. But I couldn't figure out how to play in windows env. After trying to play I get 
_>dvdnav demux error: Could not open ?E:\April 10\Pictures\Untitled(7)\index (9).mp4 with libdvdcss.
>dvdnav demux error: Can't open ?E:\April 10\Pictures\Untitled(7)\index (9).mp4 for reading
>dvdnav demux error: vm: failed to open/read the DVD
>filesystem stream error: cannot open file ‪E:\April 10\Pictures\Untitled(7)\index (9).mp4 (Invalid argument)_
Is this a known issue in this early project?

**Comment by alexmercerind** [comment]
I can't say I'm able to play everything on Windows.

**Comment by plplplpla** [comment]
It is not working with this   [URL](https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_30MB.mp4) either
And a lot of audio output errors
mmdevice audio output error: cannot initialize COM (error 0x80010106)
main input error: Your input can't be opened
 main input error: VLC is unable to open the MRL '‪https://test-videos.....

**Comment by plplplpla** [comment]
I was able to run it properly after building. It is a permission issue. Even enabling developer mode did not work. But worked after it was built.
