### ISSUE TITLE
[feature] Mpris support on Linux

### ISSUE THREAD

**Issue by BlueQuantumx** [alexmercerind/dart_vlc#5]
Could you add Mpris based on D-Bus support on Linux? So that we can use system media controller.

**Comment by alexmercerind** [comment]
I'm going to close this since this is not part of libVLC API, but related to dbus etc. For that, there is already [dbus.dart](https://github.com/canonical/dbus.dart) from Canonical itself. Rather easy to implement the `MediaPlayer2` spec.
