### ISSUE TITLE
Loopmode for playlists

### ISSUE THREAD

**Issue by syleishere** [alexmercerind/dart_vlc#50]
Be nice if this could be implemented like audio assets etc plugins have.

**Comment by alexmercerind** [comment]
It already has.

**Comment by syleishere** [comment]
Where? I can't find documentation on it.

**Comment by alexmercerind** [comment]
@syleishere  
https://github.com/alexmercerind/dart_vlc/blob/a5b043f9901621cdee5d72b6861273f1f018a415/lib/src/player.dart#L265-L275

**Comment by syleishere** [comment]
Never mind I see what you are doing in the code, assigning a future callback, I meant add a real option like audio assets:
`      await desktopPlayer!.open(new Playlist(medias: medias), autoStart: false, loop=true);
`
is what I was getting at, I guess I'll implement my own callback for now

**Comment by alexmercerind** [comment]
> Never mind I see what you are doing in the code, assigning a future callback, I meant add a real option like audio assets:
await desktopPlayer!.open(new Playlist(medias: medias), autoStart: false, loop=true);
is what I was getting at, I guess I'll implement my own callback for now

I don't really understand whatever you are saying. Current implementation has been tested for compilation (see GitHub actions) & contains way way way more methods than assets_audio_player. Please confirm yourself before pinging me here.
