### ISSUE TITLE
nowPlaying meta data on network stream not loaded

### ISSUE THREAD

**Issue by MrCustomizer** [alexmercerind/dart_vlc#58]
I've just started experimenting with this library and I like the interface a lot so far.

One thing that prevents me from integrating dart_vlc in my own project though, is that not all metadata seems to be loaded on certain streams. The content of the field "nowPlaying" is missing on the stream [http://stream-uk1.radioparadise.com/aac-128](http://stream-uk1.radioparadise.com/aac-128).

Minimal example to reproduce the problem:
```
var player = new Player(id: 0);
Media radioParadise = await Media.network(
  'http://stream-uk1.radioparadise.com/aac-128',
  parse: true,
  timeout: new Duration(seconds: 10),
);

player.open(new Playlist(medias: [radioParadise]));
print(radioParadise.metas['title']);
print(radioParadise.metas['nowPlaying']);
print(radioParadise.metas);
```

In this example the field 'title' is filled, 'nowPlaying' is empty though. This specific station does not fill its meta data correctly. Artist and title information is only visible in the field 'nowPlaying', which is why I need access to the contents of this field.

I've played around with the timeout duration, but that does not seem to change the behaviour.

Vlc itself reads the 'nowPlaying' tag correctly, so I'm guessing it's a problem with dart_vlc and not vlc itself. To verify that vlc really is reading the tag, just run `cvlc -I rc --aout=pulse http://stream-uk1.radioparadise.com/aac-128` in a terminal and type 'info' <Enter> in vlc's console after the streams has started playing. The output of vlc looks like this:

```
cvlc -I rc --aout=pulse http://stream-uk1.radioparadise.com/aac-128

VLC media player 3.0.12 Vetinari (revision 3.0.12-1-0-gd147bb5e7e)
[000055f5c72e3180] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.12 Vetinari
Command Line Interface initialized. Type `help' for help.
> [00007fe11000a900] mpeg4audio demux packetizer: AAC channels: 2 samplerate: 44100
info
+----[ Meta data ]
|
| genre: Eclectic
| filename: aac-128
| title: Radio Paradise (128k aac)
| now_playing: U2 - Sunday Bloody Sunday
|
+----[ Stream 0 ]
|
| Bits per sample: 32
| Codec: MPEG AAC Audio (mp4a)
| Sample rate: 44100 Hz
| Channels: Stereo
| Type: Audio
|
+----[ end of stream info ]

```

Additional information: I've only tried dart_vlc in Linux.

**Comment by alexmercerind** [comment]
I can't say anything about this, as of now. I parse `VLC::Media` without any changes made.

You can try to change the VLC version from CMake if that fixes it, however I cannot confirm this as an issue in plugin. Either way, metadata parsing isn't essentially a core feature of this plugin.

You can confirm this below:
		this->metas["title"]       = media.meta(libvlc_meta_Title);
		this->metas["artist"]      = media.meta(libvlc_meta_Artist);
		this->metas["genre"]       = media.meta(libvlc_meta_Genre);
		this->metas["copyright"]   = media.meta(libvlc_meta_Copyright);
		this->metas["album"]       = media.meta(libvlc_meta_Album);
		this->metas["trackNumber"] = media.meta(libvlc_meta_TrackNumber);
		this->metas["description"] = media.meta(libvlc_meta_Description);
		this->metas["rating"]      = media.meta(libvlc_meta_Rating);
		this->metas["date"]        = media.meta(libvlc_meta_Date);
		this->metas["settings"]    = media.meta(libvlc_meta_Setting);
		this->metas["url"]         = media.meta(libvlc_meta_URL);
		this->metas["language"]    = media.meta(libvlc_meta_Language);
		this->metas["nowPlaying"]  = media.meta(libvlc_meta_NowPlaying);
		this->metas["encodedBy"]   = media.meta(libvlc_meta_EncodedBy);
		this->metas["artworkUrl"]  = media.meta(libvlc_meta_ArtworkURL);
		this->metas["trackTotal"]  = media.meta(libvlc_meta_TrackTotal);
		this->metas["director"]    = media.meta(libvlc_meta_Director);
		this->metas["season"]      = media.meta(libvlc_meta_Season);
		this->metas["episode"]     = media.meta(libvlc_meta_Episode);
		this->metas["actors"]      = media.meta(libvlc_meta_Actors);
		this->metas["albumArtist"] = media.meta(libvlc_meta_AlbumArtist);
		this->metas["discNumber"]  = media.meta(libvlc_meta_DiscNumber);
		this->metas["discTotal"]   = media.meta(libvlc_meta_DiscTotal);
		this->metas["duration"]    = std::to_string(media.duration());
Notice `libvlc_meta_NowPlaying` being assigned.

```cpp
int main() {
	Media* media = Media::network(0, "http://stream-uk1.radioparadise.com/aac-128", true, 10000);
	for (const auto &pair: media->metas)
		std::cout << pair.first << " : " << pair.second << "\n";
	std::cin.get();
	return EXIT_SUCCESS;
}
```

From the above code using wrapper in this plugin, following result is generated:

```
actors :
album :
albumArtist :
artist :
artworkUrl :
copyright :
date :
description :
director :
discNumber :
discTotal :
duration : 0
encodedBy :
episode :
genre : Eclectic
language :
nowPlaying :
rating :
season :
settings :
title : Radio Paradise (128k aac)
trackNumber :
trackTotal :
url :
```

There is nothing I can do.
