### ISSUE TITLE
Failed to play video in linux

### ISSUE THREAD

**Issue by deut818** [alexmercerind/dart_vlc#63]
```flutter: no handler found for channel dart_vlc``` am only getting this error

**Comment by alexmercerind** [comment]
Platform channel messenger on Linux native code is already set up.
https://github.com/alexmercerind/dart_vlc/blob/493a55ae79fde30cacd08945ee79c7d94602a839/linux/dart_vlc_plugin.cc#L529

I don't know the cause of issue, the builds are successful, no one else has reported the same. Try to clean the project & build again.

Thanks.

**Comment by deut818** [comment]
Am using go-flutter is there any more configurations needed for my case?

**Comment by alexmercerind** [comment]
@deut818 this plugin is for official Flutter desktop embedding, not go-flutter.
