### ISSUE TITLE
How to play song at index in playlist?

### ISSUE THREAD

**Issue by syleishere** [alexmercerind/dart_vlc#65]
What is function to jump to a certain index in a playlist? I tried jump and that does not work.
Like audio assets has:
`              await audioPlayer!.playlistPlayAtIndex(index);
`

what is the dart_vlc one?

**Comment by alexmercerind** [comment]
Does not work is not a valid explaination. What do you expect to happen, provide code.

**Comment by syleishere** [comment]
When a user clicks a song to play, I am just asking how to switch to another song in playlist.

**Comment by alexmercerind** [comment]
`await player.jump(index);`
