### ISSUE TITLE
[windows] short audio file not works?

### ISSUE THREAD

**Issue by joinhc** [alexmercerind/dart_vlc#68]
when i use the example code to play a regular song file(.mp3) which time is about 2-3 minutes long.
sound is played, every thing works fine, but when i change to a very short audio file, like this word pronounciation i download from google:
https://ssl.gstatic.com/dictionary/static/pronunciation/2019-10-21/audio/br/brandish_en_us_1.mp3

then there just no sound played. what am i missing?

my environments:
[√] Flutter (Channel dev, 2.3.0-16.0.pre, on Microsoft Windows [Version 10.0.19042.1052])
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
dart_vlc: ^0.0.6

here is my code:
`
Future<void> playFile(File file) async {
	final player = Player(id: 123);
	Media media = await Media.file(file);
	return player.open(media);
}
`

thanks for the help.

**Comment by mfkl** [comment]
Please share full verbose logs

**Comment by alexmercerind** [comment]
@joinhc I can play the file you shared both as `Media.file` and `Media.network`.
