### ISSUE TITLE
Exception thrown when video is closed with controls using a Navigator.pop

### ISSUE THREAD

**Issue by amed901107** [alexmercerind/dart_vlc#69]
Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
ControlState#3a02e(ticker active) was disposed with an active Ticker.

ControlState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: Ticker(created by ControlState#3a02e(lifecycle state: created))
The stack trace when the Ticker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
#2      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:129:15)
#3      new AnimationController (package:flutter/src/animation/animation_controller.dart:247:21)
#4      ControlState.initState (package:dart_vlc/src/widgets/controls.dart:60:36)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
...     Normal element mounting (81 frames)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#88     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
#89     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
...     Normal element mounting (28 frames)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#118    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
#119    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
...     Normal element mounting (238 frames)
#357    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#358    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
#359    Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
#360    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5654:32)
#361    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
#362    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#363    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#364    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#365    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#366    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#367    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#368    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#369    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#370    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#371    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#372    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#373    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#374    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#375    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#376    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#377    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
#378    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#379    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#380    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#381    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#382    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#383    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#384    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
#385    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#386    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
#387    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#388    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#389    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#390    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
#391    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#392    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#393    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#394    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#395    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
#396    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
#397    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#398    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#399    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#400    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#404    _invoke (dart:ui/hooks.dart:163:10)
#405    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#406    _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack: 
#0      SingleTickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:142:7)
#1      SingleTickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:156:6)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
...
====================================================================================================
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4188 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4188:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
#4      ControlState._startHideTimer.<anonymous closure> (package:dart_vlc/src/widgets/controls.dart:330:7)
#5      _rootRun (dart:async/zone.dart:1346:47)
#6      _CustomZone.run (dart:async/zone.dart:1258:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)

**Comment by alexmercerind** [comment]
Hi there Amed!

Thanks for the report.

**Comment by alexmercerind** [comment]
Can you share minimal code for me to try out?

**Comment by amed901107** [comment]
Hi, if you leave a delay between the player stop and the navigator it doesn't throw the exception

**Comment by amed901107** [comment]
Widget:
import 'dart:io';

import 'package:dart_vlc/dart_vlc.dart';
import 'package:flutter/material.dart';
import 'package:guatini/helper/auxiliary_functions.dart';
import 'package:guatini/helper/route_argument.dart';
import 'package:guatini/helper/values_notifier.dart';
import 'package:guatini/resources/colors.dart';
import 'package:guatini/resources/images.dart';

class VideoFullScreenDesktop extends StatefulWidget {
  final RouteArgument routeArgument;

  VideoFullScreenDesktop({Key key, this.routeArgument}) : super(key: key);

  @override
  _VideoFullScreenDesktopState createState() {
    return _VideoFullScreenDesktopState();
  }
}

class _VideoFullScreenDesktopState extends State<VideoFullScreenDesktop> {
  Player player;
  String location;

  @override
  void dispose() {
    print("dispose");
    player?.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    location = widget.routeArgument.param;
    if (this.mounted) {
      player = new Player(id: 1234, videoWidth: 480, videoHeight: 360);
      openVideo();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: Stack(children: [
          Card(
            clipBehavior: Clip.antiAlias,
            child: new Video(
              playerId: 1234,
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              volumeThumbColor: AppColors.greenColor,
              volumeActiveColor: AppColors.greenColor,
              showControls: true,
            ),
          ),
          Align(
            alignment: Alignment.topRight,
            child: Container(
              width: 60,
              height: 60,
              child: IconButton(
                  iconSize: 60,
                  icon: Image.asset(
                    AppImages.icInfoOne,
                    color: AppColors.white().withOpacity(0.60),
                  ),
                  onPressed: () async {
                    closeFullScreen(context);
                  }),
            ),
          ),
        ]),
      ),
    );
  }

  void openVideo() async {
    player.open(
      await Media.file(
        new File(AuxiliaryFunctions.joinPathWindows(pathBd.value, location)),
      ),
      autoStart: true,
    );
  }

  void closeFullScreen(BuildContext context) async {
    await player.stop();
    if (mounted) setState(() {});
    Future.delayed(Duration(seconds: 3), () {
      // 5s over, navigate to a new page
      Navigator.of(context).pop();
    });
    // Navigator.of(context).pop();
  }
}
