### ISSUE TITLE
Media Assets on Linux not working

### ISSUE THREAD

**Issue by dsamt** [alexmercerind/dart_vlc#70]
Hi, I am able to play video from files and network on Linux, but when I try and load a video from an assets folder it does not seem to work as I get a fileSystem error. I am able to play animations using another plugin from my assets, so I am thinking there might be something up with the plugin. Hoping you may be able to help me out. Thanks.

flutter run -v
[  +50 ms] executing: uname -m
[  +42 ms] Exit code 0 from: uname -m
[    	] x86_64
[   +8 ms] executing: [/home/daniel/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[    	] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[    	] executing: [/home/daniel/flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +15 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[    	] 2.2.1
[   +8 ms] executing: [/home/daniel/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[    	] origin/stable
[    	] executing: [/home/daniel/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[    	] https://github.com/flutter/flutter.git
[ +147 ms] executing: [/home/daniel/flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[    	] stable
[ +160 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +119 ms] executing: /home/daniel/Android/Sdk/platform-tools/adb devices -l
[  +61 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[    	] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +131 ms] Skipping pub get: version match.
[  +40 ms] Found plugin audioplayers at /home/daniel/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/
[  +26 ms] Found plugin dart_vlc at /home/daniel/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[  +13 ms] Found plugin desktop_window at /home/daniel/.pub-cache/hosted/pub.dartlang.org/desktop_window-0.4.0/
[  +14 ms] Found plugin path_provider at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +4 ms] Found plugin path_provider_linux at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[  +14 ms] Found plugin path_provider_macos at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +5 ms] Found plugin path_provider_windows at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[ +170 ms] Found plugin audioplayers at /home/daniel/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/
[  +46 ms] Found plugin dart_vlc at /home/daniel/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[   +1 ms] Found plugin desktop_window at /home/daniel/.pub-cache/hosted/pub.dartlang.org/desktop_window-0.4.0/
[  +27 ms] Found plugin path_provider at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[    	] Found plugin path_provider_linux at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[    	] Found plugin path_provider_macos at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +1 ms] Found plugin path_provider_windows at /home/daniel/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[  +50 ms] Generating /home/daniel/Desktop/menu_app/new_menu/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +262 ms] Initializing file store
[  +25 ms] Skipping target: gen_localizations
[  +21 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[  +24 ms] /home/daniel/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/daniel/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/daniel/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.EQCQMP/flutter_tool.TBUEUY/app.dill --packages /home/daniel/Desktop/menu_app/new_menu/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +79 ms] Building Linux application...
[ +109 ms] <- compile package:new_menu/main.dart
[  +10 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/daniel/Desktop/menu_app/new_menu/linux
[ +361 ms] -- Configuring done
[   +1 ms] -- Generating done
[  +14 ms] -- Build files have been written to: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug
[   +9 ms] executing: ninja -C build/linux/x64/debug install
[ +112 ms] ninja: Entering directory `build/linux/x64/debug'
[ +612 ms] [1/10] Running utility command for LIBVLC_EXTRACT
[+10419 ms] [2/10] Generating /home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/daniel/Desktop/menu_app/new_menu/linux/flutter/ephemeral/flutter_linux/flutter_linux.h,
_phony_
[  +22 ms] [ +134 ms] executing: uname -m
[    	] [ +251 ms] Exit code 0 from: uname -m
[    	] [    	] x86_64
[    	] [  +16 ms] executing: [/home/daniel/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[    	] [  +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[    	] [    	] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[    	] [    	] executing: [/home/daniel/flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[    	] [  +35 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[    	] [    	] 2.2.1
[   +7 ms] [   +9 ms] executing: [/home/daniel/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[    	] [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[    	] [    	] origin/stable
[    	] [    	] executing: [/home/daniel/flutter/] git ls-remote --get-url origin
[    	] [   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[    	] [    	] https://github.com/flutter/flutter.git
[    	] [ +106 ms] executing: [/home/daniel/flutter/] git rev-parse --abbrev-ref HEAD
[    	] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[    	] [    	] stable
[    	] [  +85 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[    	] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[    	] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[    	] [   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] [    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[    	] [ +220 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[    	] [   +2 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[    	] [    	] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[    	] [   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [    	] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'PubDependencies' is not required, skipping update.
[    	] [  +59 ms] Initializing file store
[    	] [  +22 ms] Done initializing file store
[    	] [ +110 ms] Skipping target: gen_localizations
[    	] [+3337 ms] Skipping target: unpack_linux
[    	] [ +949 ms] Skipping target: kernel_snapshot
[   +2 ms] [+1133 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/daniel/Desktop/menu_app/new_menu/build/flutter_assets/kernel_blob.bin}
[    	] [ +567 ms] debug_bundle_linux-x64_assets: Complete
[   +1 ms] [+1081 ms] Persisting file store
[    	] [  +24 ms] Done persisting file store
[    	] [  +21 ms] build succeeded.
[    	] [  +25 ms] "flutter assemble" took 7,594ms.
[    	] [ +151 ms] ensureAnalyticsSent: 142ms
[    	] [    	] Running shutdown hooks
[    	] [    	] Shutdown hooks complete
[    	] [   +5 ms] exiting with code 0
[+1455 ms] [3/8] Building CXX object CMakeFiles/new_menu.dir/flutter/generated_plugin_registrant.cc.o
[ +229 ms] [4/8] Building CXX object CMakeFiles/new_menu.dir/my_application.cc.o
[+6620 ms] [5/8] Building CXX object plugins/dart_vlc/CMakeFiles/dart_vlc_plugin.dir/dart_vlc_plugin.cc.o
[ +600 ms] [6/8] Linking CXX shared library plugins/dart_vlc/libdart_vlc_plugin.so
[ +612 ms] [7/8] Linking CXX executable intermediates_do_not_run/new_menu
[   +1 ms] [7/8] Install the project...
[  +28 ms] -- Install configuration: "Debug"
[  +58 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/new_menu
[  +32 ms] -- Set runtime path of "/home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/new_menu" to "$ORIGIN/lib"
[   +2 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/icudtl.dat
[   +3 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[ +610 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/lib/libdart_vlc_plugin.so
[   +9 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/lib/libdesktop_window_plugin.so
[   +4 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/assets
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/assets/images
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/assets/images/girl_running.png
[   +4 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/assets/images/smb_mario_sheet.png
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/assets/FPS_test.mkv
[  +22 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/assets/butterfly.mp4
[   +3 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/packages
[   +7 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[ +115 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[   +4 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[   +1 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[  +13 ms] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[    	] -- Installing: /home/daniel/Desktop/menu_app/new_menu/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +21 ms] Building Linux application... (completed in 22.1s)
[+1238 ms] Observatory URL on device: http://127.0.0.1:37403/C2lJkeUBYYo=/
[  +37 ms] Caching compiled dill
[ +328 ms] Connecting to service protocol: http://127.0.0.1:37403/C2lJkeUBYYo=/
[ +533 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:37403/C2lJkeUBYYo=/.
[ +238 ms] DDS is listening at http://127.0.0.1:41893/09XDKtuGXgk=/.
[ +213 ms] Successfully connected to service protocol: http://127.0.0.1:37403/C2lJkeUBYYo=/
[  +52 ms] DevFS: Creating new filesystem on the device (null)
[  +59 ms] DevFS: Created new filesystem on the device (file:///tmp/new_menuVKCVKU/new_menu/)
[   +4 ms] Updating assets
[ +282 ms] Syncing files to device Linux...
[   +7 ms] <- reset
[    	] Compiling dart to kernel with 0 updated files
[   +8 ms] <- recompile package:new_menu/main.dart e01aa5e3-077b-462c-9261-51ecd73cef52
[   +8 ms] <- e01aa5e3-077b-462c-9261-51ecd73cef52
[ +519 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[   +4 ms] Syncing files to device Linux... (completed in 549ms)
[    	] Synced 0.0MB.
[   +4 ms] <- accept
[  +21 ms] Connected to _flutterView/0x2a58ef0.
[  +27 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +5 ms] R Hot restart.
[    	] h Repeat this help message.
[    	] d Detach (terminate "flutter run" but leave application running).
[    	] c Clear the screen
[    	] q Quit (terminate the application on the device).
[   +3 ms] Running with unsound null safety
[    	] For more information see https://dart.dev/null-safety/unsound-null-safety
[    	] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:41893/09XDKtuGXgk=/
[ +996 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A41893%2F09XDKtuGXgk%3D%2F
[+6384 ms] [00007f1ba44558c0] filesystem stream error: cannot open file //tmpassets/butterfly.mp4 (No such file or directory)
[   +6 ms] [00000000025e6c40] main input error: Your input can't be opened
[    	] [00000000025e6c40] main input error: VLC is unable to open the MRL 'file:////tmpassets/butterfly.mp4'. Check the log for details.
[+6665 ms] Service protocol connection closed.
[  +16 ms] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///tmp/new_menuVKCVKU/new_menu/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 41,357ms.
[  +82 ms] ensureAnalyticsSent: 77ms
[    	] Running shutdown hooks
[    	] Shutdown hooks complete
[    	] exiting with code 0

**Comment by alexmercerind** [comment]
Hello @dsamt !

Please try out the latest version from git, do not forget to run `flutter clean` before.

Or you can manually edit file as in the above commit.

Thanks. Have great day.
