### ISSUE TITLE
Video Widget: setState being called after being dismounted from Widget tree.

### ISSUE THREAD

**Issue by MattiaudaNicolasCN** [alexmercerind/dart_vlc#75]
I'm using this package for streaming multiple cameras on a page of my Flutter App. With the new version  (**0.0.8**) I'm facing a problem, I see all the images of the `Player`s in a single `Video`, but in my code I create more than one `Video`.  With the old version (**0.0.7**) I haven't this problem and the code was the same, with the `async `and the `await `calls obviously.

Below there is the code of my Streaming page:

```
class CameraScreen extends StatefulWidget {
  CameraScreen(
      {required Key key,
      required this.onPageChange,
      required this.onLogout,
      required this.id})
      : super(key: key);
  final Function(String, String) onPageChange;
  final VoidCallback onLogout;
  final String id;
  @override
  CameraScreenState createState() => CameraScreenState();
}

class CameraScreenState extends State<CameraScreen>
    with TickerProviderStateMixin {
  PageConfig pageConfig = PageConfig();
  String project = '';
  List<ResponsiveGridCol> children = [];
  List<Player> players = [];
  List<dynamic> items = [];
  double initialSliderValue = 0;


  @override
  void initState() {
    DartVLC.initialize();

    project = Project.getCurrentProject();
    pageConfig = Project.getProjectPageDetails(widget.id);
    getData();
    super.initState();
  }

  @override
  void dispose() {
    stopAndDisposePlayers();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CustomScaffold(
      text: pageConfig.name!,
      onPageChange: widget.onPageChange,
      onLogout: widget.onLogout,
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SingleChildScrollView(
          child: ResponsiveGridRow(
            children: children,
          ),
        ),
      ),
    );
  }

  void getData() {
    File cameraFile = File(AppStrings.CONFIG_DIRECTORY_PATH +
        project +
        AppStrings.CAMERA_CONFIG_FILE_NAME);
    items = jsonDecode(cameraFile.readAsStringSync());
    List<Video> videos = [];
    List<ResponsiveGridCol> widgets = [];
    for (int i = 0; i < items.length; i++) {
      var cameraConfig = Camera.fromJson(items[i]);
      Player player = Player(id: 100 + i, videoWidth: 400, videoHeight: 300);
      var media = Media.network(cameraConfig.url,
          parse: true, timeout: Duration(seconds: 2));
      player.open(media);
      player.play();
      players.add(player);
      var video = Video(
        playerId: 100 + i,
        width: 500,
        height: 375,
        showControls: false,
      );
      videos.add(video);
      widgets.add(
        ResponsiveGridCol(
          lg: 6,
          child: Card(
            child: Column(
              children: [
                Text(cameraConfig.title, style: AppStyles.BOLD),
                Text(AppStrings.CAMERAS_TEXT),
                video,
                Divider(),
                IconButton(
                  icon: Icon(Icons.open_in_browser),
                  onPressed: () {
                  },
                )
              ],
            ),
          ),
        ),
      );
    }
    for (var item in videos) {
      print(item.playerId);
    }
    if (mounted) {
      setState(() {
        children = widgets;
      });
    }
  }


  void stopAndDisposePlayers() {
    for (var player in players) {
      player.stop();
      player.dispose();
    }
  }
}
```

**Comment by alexmercerind** [comment]
Hello there!
Thanks a lot for your report, the new version is completely migrated FFI & is nearly written from scratch.
There are few issues that I'm aware of & this is one of those.
Please stay on 0.0.7 till then.

I couldn't find a way to send video frame (`uint8_t*`) along with playerId in the new FFI interface as of now, so had to hardcode it to 0.

Thankyou.
Sorry for the inconvenience.

**Comment by MattiaudaNicolasCN** [comment]
Now I get this with the same code of yesterday:

**Comment by alexmercerind** [comment]
@MattiaudaNicolasCN are you using git version? Please ensure that `dart_vlc_ffi` is also updated to 0.0.5.

**Comment by alexmercerind** [comment]
@MattiaudaNicolasCN You may manually edit following line.
https://github.com/alexmercerind/dart_vlc/blob/d6d809a160f18beb292369759d0696a6c313e702/ffi/lib/src/internal/ffi.dart#L271

**Comment by MattiaudaNicolasCN** [comment]
Ah ok thank you. Now I wait for the 0.0.9!

**Comment by alexmercerind** [comment]
@MattiaudaNicolasCN 0.0.9 is up. Please inform if you see any issues.

**Comment by MattiaudaNicolasCN** [comment]
Now when I change  from the `CameraScreen `to another page I get the `Exception ` below for each `Video` that I've got in the page:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: setState() called after dispose(): VideoState#33feb(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
```

**Comment by alexmercerind** [comment]
@MattiaudaNicolasCN is this same as #69 ?
If yes, then it is a Dart side issue only.

**Comment by MattiaudaNicolasCN** [comment]
Yes it is similar, but I don't use `Navigator.pop()` as you can see from the code above...

**Comment by MattiaudaNicolasCN** [comment]
I also get this error now...always with the same come above:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      DartVLC.initialize.<anonymous closure>
package:dart_vlc/dart_vlc.dart:34
#2      receiver.<anonymous closure>
package:dart_vlc_ffi/…/internal/ffi.dart:271
#3      _rootRunUnary (dart:async/zone.dart:1370:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
```

It's part of Dart side issue?

**Comment by MattiaudaNicolasCN** [comment]
Do you have any update? Thanks

**Comment by alexmercerind** [comment]
@MattiaudaNicolasCN everything is working fine for me in the example application. I'm not sure what could be wrong for you.
I recommend to have a look & give example that produces the error. I cannot use the snippet you gave above due to imports etc.

**Comment by alexmercerind** [comment]
Okay apologies. Now fixed everything on master.

**Comment by alexmercerind** [comment]
You may use the git version. And report if you see something wrong. Not updating on pub.dev yet.

**Comment by sobhan15** [comment]
### same issue,any solution?

> with the same code above and the newer version (**0.1.0**) I continue to get the same error:
> 
> > FlutterError (setState() called after dispose(): VideoState#f8be5(lifecycle state: defunct, not mounted)
> > This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
> > The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
> > This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().)

**Comment by alexmercerind** [comment]
Finally, no more setState after dispose. Use 0.1.1.
