### ISSUE TITLE
Can't build for web when dart_vlc is included

### ISSUE THREAD

**Issue by jonafeucht** [alexmercerind/dart_vlc#78]
This is a known issue with ffi and not dart_vlc directly, but since dart_vlc depends on ffi building for web is impossible.

I tried it with conditions but to no avail. Even just adding `import 'package:dart_vlc/dart_vlc.dart';` breaks it for web...

```dart
import 'package:flutter/material.dart';
import 'package:dart_vlc/dart_vlc.dart';

void main() {
  runApp(DartVLCExample());
}

class DartVLCExample extends StatefulWidget {
  @override
  DartVLCExampleState createState() => DartVLCExampleState();
}

class DartVLCExampleState extends State<DartVLCExample> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('dart_vlc'),
          centerTitle: true,
        ),
        body: Text("Test"),
      ),
    );
  }
}

```

No idea if the Flutter team is every going to fix this, since this a quite old known [issue](https://github.com/flutter/flutter/issues/43898).
Is there a workaround from your side or should I just downgrade back to 0.0.7?

**Comment by alexmercerind** [comment]
@jonafeucht 
is this something that might help you out?
https://stackoverflow.com/questions/60387067/unable-to-build-flutter-web-and-flutter-mobile-apps-seperately

**Comment by jonafeucht** [comment]
Interesting, haven't thought of doing it with conditional imports. Will give it a try. Thanks
