### ISSUE TITLE
'filesystem' file not found

### ISSUE THREAD

**Issue by lixiang4543** [alexmercerind/dart_vlc#8]
Start the error：

linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/../dartvlc/internal/../mediasource/media.hpp:13:10: fatal error: 'filesystem' file not found

System info:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by alexmercerind** [comment]
This means that, the C++ standard wasn't 17 for some reason on your system.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/dart_vlc/blob/78e395e22f2f57682cb40f4f4691eec337ea13d2/linux/CMakeLists.txt#L11

But, I have already defined it. So, its not an issue on my part.

**Comment by alexmercerind** [comment]
Your distro is also very dated.
See [this](https://askubuntu.com/questions/1113974/using-c17-with-clang-on-ubuntu-16-04) work around.

**Comment by markotikvic** [comment]
For anyone else still bumping into this, try this for fix:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9 g++-9
```

**Comment by alexmercerind** [comment]
> For anyone else still bumping into this, try this for fix:
> 
> ```
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt update
> sudo apt install gcc-9 g++-9
> ```
> 
> Ubuntu 18.04

Now we don't use `std::filesystem` anywhere, that header is redundantly included. Even removing that will work.
