### ISSUE TITLE
Requiring a newer version of CMake than Flutter requires is going to cause issues

### ISSUE THREAD

**Issue by MattiaudaNicolasCN** [alexmercerind/dart_vlc#81]
Referring to this issue that I opened to Flutter: https://github.com/flutter/flutter/issues/86852 would just like to notify you too. 

Because on Linux I will get this:

> CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:8 (cmake_minimum_required):
> CMake 3.15 or higher is required. You are running version 3.10.2

**Comment by alexmercerind** [comment]
Okay, I have downgraded version to 3.10 now, should work fine now. Another reason to not use snap.

**Comment by drexhacker** [comment]
@alexmercerind Thanks a lot this has saved me.

**Comment by MattiaudaNicolasCN** [comment]
You are again requiring a higher version of CMake on Linux. My version of Flutter is **2.5.1**. Now I get this:

> CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/CMakeLists.txt:1 (cmake_minimum_required):
>   CMake 3.13 or higher is required.  You are running version 3.10.2
> 
> 
> Exception: Unable to generate build files

Please downgrade it...

**Comment by alexmercerind** [comment]
> You are again requiring a higher version of CMake on Linux. My version of Flutter is 2.5.1. Now I get this.

Don't use snap.
