### ISSUE TITLE
How to set volume for only a specific player?

### ISSUE THREAD

**Issue by jonafeucht** [alexmercerind/dart_vlc#90]
Say I have two players:
Player player1 = Player(id: 1);
Player player2 = Player(id: 2);

If I change the volume of player1 it will also change the volume for player2, which shouldn't happen.

**Comment by DomingoMG** [comment]
@jonafeucht It really is a strange thing.

I also had this problem, according to the LibVLC developers they say they should apply how a VLC player works, a separate volume per player.

But I have noticed that the volume is applied to all the players, the solution assigns an output device without being the default and you will be able to manage the volume independently.

It is not the correct solution but it works for me. The ideal is to watch without in C ++ allows you to control the volume independently per player.

**Comment by alexmercerind** [comment]
Currently volume control isn't very good. I have to look libVLC APIs before claiming anything. Marking as "good first issue" aswell.

**Comment by DomingoMG** [comment]
I have not been able to check it 100%.
On the VLC forums there is a post from a person who has the same problem allocating the volume.

Command line:
**--aout=direcsound**
--aout {any, mmdevice, directsound, waveout, amem, afile, adummy, none}

read more here:
https://forum.videolan.org/viewtopic.php?t=147229

I will try it if it works

**Comment by KyleKun** [comment]
@DomingoMG could you get it to work?

**Comment by DomingoMG** [comment]
@KyleKun I currently don't have a solution per player.
I just know that if you assign a different output device to the player it becomes independent without affecting the other player.

It would be necessary to see if @alexmercerind could look for some type of complement that allows to differentiate the volume of the player.

In case of finding a better solution, I will send it to you.

**Comment by trapeye** [comment]
> @KyleKun I currently don't have a solution per player. I just know that if you assign a different output device to the player it becomes independent without affecting the other player.
> 
> It would be necessary to see if @alexmercerind could look for some type of complement that allows to differentiate the volume of the player.
> 
> In case of finding a better solution I will post it here.

found solution?

**Comment by DomingoMG** [comment]
@trapeye  It didn't accomplish much but it was able to apply a separate volume per player via command line.
What I can't do is update the directx sound as a setVolume, I don't know if @alexmercerind will be able to contribute something.

COMMAND LINE:
```
vlc.exe "D:\tracks\Melendi - La Chica Perfecta.mp3" **--directx-volume=0.35**
````

DART:
```
Player _player = Player(id: id, commandlineArguments: ['--aout=directsound', '--directx-volume=0.35']);
```

REMOVE INITIAL VOLUME IN C++:
![image](https://user-images.githubusercontent.com/36201422/151647120-45e85b2f-3231-41e8-9fc1-7bbc8ee97a51.png)

**Comment by DomingoMG** [comment]
Hi @alexmercerind, you could let the user decide if it's directx-Sound, the setdevice is without {0.0.0.0.0}. and if it is mmdevice it is with {0.0.0.0.0}...

The documentation indicates that depending on the type it corresponds in one way or another.

![image](https://user-images.githubusercontent.com/36201422/151663550-6c806422-0483-4853-b388-d983bfc59f4f.png)

**Comment by trapeye** [comment]
> @trapeye, @alexmercerind, @KyleKun, @jonafeucht
> 
> **SOLUTION FOUND:** You will only have to instantiate the player as I indicate and you will be able to adjust the volume independently and with Alex's implementation of setVolume you will change the volume.
> 
> I must indicate that I have spent days looking for millions of solutions, it has worked for me, I would appreciate a thumbs up.
> 
> COMMAND LINE:
> 
> ```batchfile
> vlc.exe "D:\tracks\Melendi - La Chica Perfecta.mp3" --aout=directsound --directx-volume=0.35
> ```
> 
> DART:
> 
> ```dart
> Player _player1 = Player(id: id, commandlineArguments: ['--aout=directsound', '--directx-volume=0.35']);
> _player1.open(....Media.....);
> _player1.setVolume(1.0);
> 
> Player _player2 = Player(id: id, commandlineArguments: ['--aout=directsound', '--directx-volume=0.35']);
> _player2.open(....Media.....);
> _player2.setVolume(0.50);
> ```
> 
> REMOVE INITIAL VOLUME IN C++: **DART_VLC/player.h**
> 
> ![image](https://user-images.githubusercontent.com/36201422/151647120-45e85b2f-3231-41e8-9fc1-7bbc8ee97a51.png)

The command line not work
