### ISSUE TITLE
Metadata parsing crashes on Windows

### ISSUE THREAD

**Issue by mytja** [alexmercerind/dart_vlc#92]
Hello!
This is very interesting...
[v0.1.1](https://github.com/alexmercerind/dart_vlc/releases/tag/v0.1.1) promises that metadata parsing has been fixed, but not for me. If I run metadata parsing, my app crashes without any notification. If I checkout dart_vlc to [this](https://github.com/alexmercerind/dart_vlc/commit/c1c460b687b05936d52ab1d086a5b19dd3ac7b5e#diff-cbaeff3d4c7eebdc70018d11591c01a9fe591370aaad87eb498742d88d7fa3cd) commit, it works just fine...
I don't know what can be wrong, but it really seems that I need [this](https://github.com/alexmercerind/dart_vlc/commit/c1c460b687b05936d52ab1d086a5b19dd3ac7b5e#diff-cbaeff3d4c7eebdc70018d11591c01a9fe591370aaad87eb498742d88d7fa3cd) line.
But this happens only in debug mode, not in release mode...
Thank you so much

**Comment by mytja** [comment]
EDIT:
App crashes also when you jump to any other song in playlist & when song is over and it plays next one in playlist.

I am running Windows 11 - latest Beta Channel Preview release

**Comment by alexmercerind** [comment]
@mytja are you on latest version of dart_vlc (0.1.1) and dart_vlc_ffi (0.1.0)? These bugs were somehow introduced, but should be fixed now.

**Comment by mytja** [comment]
Hello!
Yes, now it suddenly works if I clone latest from git. It was very strange.
Anyways thank you so much for your support

**Comment by alexmercerind** [comment]
> Yes, now it suddenly works if I clone latest from git.

Is the `pub.dev` version still broken? Did I mess up publishing? Please let me know if you experienced problem there.
Thankyou.

**Comment by Zarainia** [comment]
The latest version on pub.dev (0.1.1?) causes a crash, I think when the media is loaded. I'm not actually doing any metadata parsing. Version 0.1.0 works fine (apart from the autostart issue I was experiencing). The GitHub version does not crash, but it is also not playing audio on `playOrPause()` for me. All of this is with the same app, just changing the package version.

**Comment by alexmercerind** [comment]
WIP

**Comment by alexmercerind** [comment]
Use 0.1.2. It also comes with a lot performance improvement for Video widget.
