### ISSUE TITLE
LateInitializationError: Field 'dynamicLibrary' has not been initialized.

### ISSUE THREAD

**Issue by amed901107** [alexmercerind/dart_vlc#97]
Error using in windows
When the exception was thrown, this was the stack: 
#0      dynamicLibrary (package:dart_vlc_ffi/src/internal/dynamiclibrary.dart)
#1      PlayerFFI.create (package:dart_vlc_ffi/src/internal/ffi.dart:21:42)
#2      PlayerFFI.create (package:dart_vlc_ffi/src/internal/ffi.dart)
#3      new Player (package:dart_vlc_ffi/src/player.dart:101:15)

**Comment by alexmercerind** [comment]
Could you please try `flutter clean`?
If it does not work, please show the contents of your build/windows/runner/Debug folder.

**Comment by alexmercerind** [comment]
![image](https://user-images.githubusercontent.com/28951144/128896026-f88820c6-a44c-46a0-8397-f5afe75229b5.jpg)

See the difference in size of `dart_vlc_plugin.dll`.

**Comment by amed901107** [comment]
the version I was using was 0.0.7.using the last lib it gives me the following compiling error
![image](https://user-images.githubusercontent.com/49206173/128899112-d60a9c07-a088-42ad-a0d6-c9e3889d9b7d.png)
![image](https://user-images.githubusercontent.com/49206173/128899214-12f03902-7d86-4c56-9637-09c411a00b74.png)

**Comment by amed901107** [comment]
![image](https://user-images.githubusercontent.com/49206173/128901231-cea25aec-3b14-4f37-8d6d-b36b2478e72c.png)
I already solved with this line of code and version0.0.7, I did not know that there was that change in that version. Thanks for everything

**Comment by alexmercerind** [comment]
Okay. Hope your issue is fixed.

Closing the issue. There have been changes to core functionality of the library, so changes to API were necessary.
Thankyou.

**Comment by ksajan** [comment]
I am getting the same error while using the example given by you. I am using macOS with Flutter version: 2.10.3.

**Comment by alexmercerind** [comment]
> I am getting the same error while using the example given by you. I am using macOS with Flutter version: 2.10.3. And this was the stack when the exception was thrown:
> 
> ```
> The following LateError was thrown attaching to the render tree:
> LateInitializationError: Field 'dynamicLibrary' has not been initialized.
> 
> When the exception was thrown, this was the stack:
> #0      dynamicLibrary (package:dart_vlc_ffi/src/internal/dynamiclibrary.dart)
> #1      PlayerFFI.create (package:dart_vlc_ffi/src/internal/ffi.dart:19:42)
> #2      PlayerFFI.create (package:dart_vlc_ffi/src/internal/ffi.dart)
> #3      new Player (package:dart_vlc_ffi/src/player.dart:130:15)
> #4      new Player (package:dart_vlc/dart_vlc.dart:70:8)
> #5      new DartVLCExampleState (package:flutter_vlc/main.dart:18:19)
> #6      DartVLCExample.createState (package:flutter_vlc/main.dart:14:40)
> #7      new StatefulElement (package:flutter/src/widgets/framework.dart:4842:25)
> #8      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:770:38)
> #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3785:40)
> #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
> #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
> #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
> #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
> #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
> #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
> #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
> #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
> (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
> ```

Don't say anything without code.

Did you add?
```dart
DartVLC.initialize();
```

**Comment by ksajan** [comment]
Yes, I did. I used the same code given in the example. That's why I didn't add the code here. Should I add?

**Comment by alexmercerind** [comment]
> Yes, I did. I used the same code given in the example. That's why I didn't add the code here. Should I add?

If the example app reproduces the same, then I can help otherwise not (it's your fault then).

**Comment by ksajan** [comment]
I tried the example on both macOS and Windows both were throwing the same error.
