### ISSUE TITLE
libvlc.dll missing

### ISSUE THREAD

**Issue by jnschulze** [alexmercerind/dart_vlc#98]
Hi,
I just added this plugin (version `0.1.2`) to an empty project's pubspec, however, the app won't start on Windows due to `libvlc.dll` being missing.  I saw that VLC is now bundled with the plugin so some path might be wrong in `windows/CMakeLists.txt`.

Btw., is there a particular reason for bundling VLC with this plugin? I'd prefer to stick with the previous approach, i.e. downloading it from a trusted source on demand.

**Comment by alexmercerind** [comment]
@jnschulze I had to package libVLC binaries within the plugin because there were few people getting errors while build. Apparently GitHub is banned in China & sometimes VideoLAN servers send corrupt files.
